- platform: "mqtt"
  unique_id: xiaomi_bathroom_underlight_button_availability
  name: Кнопка подсветки (Ванная)_availability
  state_topic: "zigbee2mqtt/bathroom_underlight_button/availability"
  
- platform: "mqtt"
  unique_id: xiaomi_bathroom_underlight_button_battery
  name: Кнопка подсветки (Ванная)_battery
  state_topic: "zigbee2mqtt/bathroom_underlight_button"
  availability_topic: "zigbee2mqtt/bathroom_underlight_button/availability"
  unit_of_measurement: "%"
  value_template: "{{ value_json.battery }}"
  device_class: "battery"

- platform: "mqtt"
  unique_id: xiaomi_bathroom_underlight_button_action
  name: Кнопка подсветки (Ванная)_action
  state_topic: "zigbee2mqtt/bathroom_underlight_button"
  availability_topic: "zigbee2mqtt/bathroom_underlight_button/availability"
  value_template: "{{ value_json.action }}"
  icon: "mdi:gesture-double-tap"

# - platform: "mqtt"
#   unique_id: xiaomi_bathroom_underlight_button_signal
#   name: Кнопка подсветки (Ванная)_signal
#   state_topic: "zigbee2mqtt/bathroom_underlight_button"
#   availability_topic: "zigbee2mqtt/bathroom_underlight_button/availability"
#   unit_of_measurement: "lqi"
#   value_template: "{{ value_json.linkquality }}"
#   icon: "mdi:signal"
