- platform: template
  sensors:
    hall_thermostat_availability_problem:
      friendly_name: "Теплый пол (Ванная)_availability_problem"
      icon_template: > 
        {% if is_state('sensor.hall_thermostat_availability', 'offline') %}
          mdi:car-brake-alert 
        {% else %}
          mdi:car-brake-worn-linings
        {% endif %}
      value_template: >
        {% if is_state('sensor.hall_thermostat_availability', 'offline') %}
          ON
        {% else %}
          OFF
        {% endif %}
      device_class: "problem"