- alias: "[ OCCUPANCY ] - Включать свет по датчику движения (Кухня)"
  id: kitchen_occupancy_light
  trigger:
    - platform: state
      entity_id: binary_sensor.datchik_dvizheniia_kukhnia
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.auto_lights_motion
      state: "on"
    - condition: state
      entity_id: group.iphone_focus
      state: "on"
  action:
    - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.datchik_dvizheniia_kukhnia
            state: 'on'
          - condition: state
            entity_id: group.my_device_trackers
            state: home
          - condition: state
            entity_id: group.kitchen_lights
            state: 'off'
        sequence:
          - service: light.turn_on
            data:
              transition: 0
              brightness_pct: 100
            target:
              entity_id: light.yeelight_strip6_0x12ed5ce2
          - service: light.turn_on
            data:
              transition: 0
              brightness_pct: 100
            target:
              entity_id: light.yeelight_ceila_0x1a5b20e7_nightlight


- alias: "[ OCCUPANCY ] - Выключать свет по датчику движения 5 минут (Кухня)"
  id: kitchen_occupancy_light_off_5min
  trigger:
    - platform: state
      entity_id: binary_sensor.datchik_dvizheniia_kukhnia
      to: 'off'
      for: 00:05:00
  condition:
    - condition: state
      entity_id: input_boolean.auto_lights_motion
      state: "on"
  action:
    - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.datchik_dvizheniia_kukhnia
            state: 'off'
          - condition: state
            entity_id: light.yeelight_ceila_0x1a5b20e7_nightlight
            state: 'on'
        sequence:
          - service: light.turn_off
            target:
              entity_id: light.yeelight_strip6_0x12ed5ce2
            data:
              transition: 0
          - service: light.turn_off
            data:
              transition: 0
            target:
              entity_id: light.yeelight_ceila_0x1a5b20e7_nightlight


- alias: "[ OCCUPANCY ] - Выключать свет по датчику движения 30 минут (Кухня)"
  id: kitchen_occupancy_light_off_30min
  trigger:
    - platform: state
      entity_id: binary_sensor.datchik_dvizheniia_kukhnia
      to: 'off'
      for: 00:30:00
  action:
    - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.datchik_dvizheniia_kukhnia
            state: 'off'
          - condition: state
            entity_id: group.kitchen_lights
            state: 'on'
        sequence:
          - service: light.turn_off
            target:
              entity_id: group.kitchen_lights
            data:
              transition: 0
          - service: light.turn_off
            data:
              transition: 0
            target:
              entity_id: light.yeelight_ceila_0x1a5b20e7_nightlight