- alias: "[ TIME ] - Переводить все устройства в бесшумный режим в 11 вечера"
  id: set_device_silent_mode_at_11pm
  trigger:
    platform: time
    at: "23:00:00"
  condition: []
  action:
    - service: fan.set_preset_mode
      entity_id: fan.zhimi_ma4_39fd_air_purifier
      data:
        preset_mode: Sleep
    - service: vacuum.set_fan_speed
      entity_id: vacuum.xiaomi_1c
      data:
        fan_speed: Silent
    - service: climate.set_fan_mode
      target:
        entity_id: climate.midea_ac_30786326300484
      data:
        fan_mode: Silent
    - service: climate.set_fan_mode
      target:
        entity_id: climate.midea_ac_30786325663901
      data:
        fan_mode: Auto
    - service: homeassistant.turn_off
      data: 
        entity_id: light.deerma_jsq5_dbeb_indicator_light
        
- alias: "[ TIME ] - Переводить все устройства в нормальный режим в 11 утра"
  id: set_device_normal_mode_at_11am
  trigger:
    platform: time
    at: "11:00:00"
  condition: []
  action:
    - service: fan.set_preset_mode
      entity_id: fan.zhimi_ma4_39fd_air_purifier
      data:
        preset_mode: Auto
    - service: vacuum.set_fan_speed
      entity_id: vacuum.xiaomi_1c
      data:
        fan_speed: Standard
    - service: climate.set_fan_mode
      target:
        entity_id: climate.midea_ac_30786326300484
      data:
        fan_mode: Auto
    - service: climate.set_fan_mode
      target:
        entity_id: climate.midea_ac_30786325663901
      data:
        fan_mode: Auto
    - service: homeassistant.turn_on
      data: 
        entity_id: light.deerma_jsq5_dbeb_indicator_light
        
