# Детская #######################################
- alias: "[Влажность (Детская)] - низкая alert (окна закрыты)"
  id: bb3a7df3-4321-4ebe-8b49-bc9ba69ad2b6
  mode: single
  trigger:
    - platform: template
      value_template: "{{ (states('sensor.aqara_cabinet_temperature_humidity') | float) < 50 }}"
      for:
        minutes: 30
  condition:  
    - condition: state
      entity_id: binary_sensor.cabinet_left_window_contact
      state: "off"
    - condition: state
      entity_id: binary_sensor.cabinet_right_window_contact
      state: "off"
    - condition: state
      entity_id: input_boolean.auto_climate
      state: "off"
  action:
    - service: telegram_bot.send_message
      data:
        title: "<b>Влажность в детской</b>"
        message: >-
          {% if (trigger.to_state.state | float) > 70 -%} Повышенная влажность,
          {% elif (trigger.to_state.state | float) < 50 -%} Пониженная влажность,
          {% endif -%} влажность: <b>{{ trigger.to_state.state }}</b>
        target:
          - !secret telegram_id_1
          - !secret telegram_id_2
        disable_notification: false
        
    - service: notify.mobile_app_iphone_amnezia
      data:
        title: Датчик влажности воздуха
        message: "{{ '\ud83d\udca7' }} Влажность в детской изменилась, и составляет:  {{ states('sensor.aqara_cabinet_temperature_humidity') }}"
        data:
          actions:
            - action: "HUMIDIFIERON"
              title: "Включить увлажнитель"
            - action: "HUMIDIFIERON1H"
              title: "Включить увлажнитель на 1 час"
            - action: "HUMIDIFIERPASS"
              title: "Пропустить"
              destructive: true
            
            
    - delay: 9000
    
    
- alias: "[Влажность (Детская)] - высокая alert (окна закрыты)"
  mode: single
  id: bb3a8df3-8920-4ebe-8b49-bc9b88sad2b6
  trigger:
    - platform: template
      value_template: "{{ (states('sensor.aqara_cabinet_temperature_humidity') | float) > 70 }}"
      for:
        minutes: 30       
  condition:  
    - condition: state
      entity_id: "binary_sensor.cabinet_left_window_contact"
      state: "off"
    - condition: state
      entity_id: "binary_sensor.cabinet_right_window_contact"
      state: "off"
    - condition: state
      entity_id: input_boolean.auto_climate
      state: "off"
  action:
    - service: telegram_bot.send_message
      data:
        title: "<b>Влажность в детской</b>"
        message: >-
          {% if (trigger.to_state.state | float) > 70 -%} Повышенная влажность,
          {% elif (trigger.to_state.state | float) < 50 -%} Пониженная влажность,
          {% endif -%} влажность: <b>{{ trigger.to_state.state }}</b>
        target:
          - !secret telegram_id_1
          - !secret telegram_id_2
        disable_notification: false
        
    - service: notify.mobile_app_iphone_amnezia
      data:
        title: Датчик влажности воздуха
        message: "{{ '\ud83d\udca7' }} Влажность в детской изменилась, и составляет:  {{ states('sensor.aqara_cabinet_temperature_humidity') }}"
        data:
          actions:
            - action: ACONFAN
              title: "Включить увлажнитель"
              destructive: no
            - action: ACONFANON1H
              title: "Включить увлажнитель на 1 час"
              destructive: no
            - identifier: ACONFANPASS
              title: "Пропустить"
              destructive: true
            
    - delay: 9000
    
# # Зал ####################################### 

- alias: "[Влажность (Зал)] - низкая alert (окна закрыты)"
  mode: single
  id: 8akq74h3-3e20-4ebe-8b49-bcddd69ad2b6
  trigger:
    - platform: template
      value_template: "{{ (states('sensor.livingroom_temperature_humidity') | float) < 50 }}"
      for:
        minutes: 30
  condition:
    - condition: state
      entity_id: "binary_sensor.cabinet_left_window_contact"
      state: "off"
    - condition: state
      entity_id: "binary_sensor.cabinet_right_window_contact"
      state: "off"
    - condition: state
      entity_id: input_boolean.auto_climate
      state: "off"
  action:
    - service: telegram_bot.send_message
      data:
        title: "<b>Влажность в зале</b>"
        message: >-
          {% if (trigger.to_state.state | float) > 70 -%} Повышенная влажность,
          {% elif (trigger.to_state.state | float) < 50 -%} Пониженная влажность,
          {% endif -%} влажность: <b>{{ trigger.to_state.state }}</b>
        target:
          - !secret telegram_id_1
          - !secret telegram_id_2
        disable_notification: false
    
    - service: notify.mobile_app_iphone_amnezia
      data:
        title: Датчик влажности воздуха
        message: "{{ '\ud83d\udca7' }} Влажность в зале изменилась, и составляет:  {{ states('sensor.livingroom_temperature_humidity') }}"
        data:
          actions:
            - action: HUMIDIFIERON
              title: "Включить увлажнитель"
              activationMode: "background"
              destructive: no
              behavior: "default"
            - action: HUMIDIFIERON1H
              title: "Включить увлажнитель на 1 час"
              activationMode: "background"
              destructive: no
            - action: HUMIDIFIERPASS
              title: "Пропустить"
              destructive: true
    
    - delay: 9000
    
    
- alias: "[Влажность (Зал)] - высокая alert (окна закрыты)"
  mode: single
  id: bb3a7df3-3e20-4ebe-8b49-bcjfye63yqd6
  trigger:
    - platform: template
      value_template: "{{ (states('sensor.livingroom_temperature_humidity') | float) > 70 }}"
      for:
        minutes: 30
  condition:
    - condition: state
      entity_id: "binary_sensor.cabinet_left_window_contact"
      state: "off"
    - condition: state
      entity_id: "binary_sensor.cabinet_right_window_contact"
      state: "off"
    - condition: state
      entity_id: input_boolean.auto_climate
      state: "off"
  action:
    - service: telegram_bot.send_message
      data:
        title: "<b>Влажность в зале</b>"
        message: >-
          {% if (trigger.to_state.state | float) > 70 -%} Повышенная влажность,
          {% elif (trigger.to_state.state | float) < 50 -%} Пониженная влажность,
          {% endif -%} влажность: <b>{{ trigger.to_state.state }}</b>
        target:
          - !secret telegram_id_1
          - !secret telegram_id_2
        disable_notification: false
    
    - service: notify.mobile_app_iphone_amnezia
      data:
        title: Датчик влажности воздуха
        message: "{{ '\ud83d\udca7' }} Влажность в зале изменилась, и составляет:  {{ states('sensor.livingroom_temperature_humidity') }} "
        data:
          actions:
            - action: HUMIDIFIERON
              title: "Включить увлажнитель"
              activationMode: "background"
              destructive: no
              behavior: "default"
            - action: HUMIDIFIERON1H
              title: "Включить увлажнитель на 1 час"
              activationMode: "background"
              destructive: no
            - action: HUMIDIFIERPASS
              title: "Пропустить"
              destructive: true
            
    - delay: 9000
    
# ################# ACTIONABLE NOTIFICATIONS ######################## 
- id: push_notify_humidifier_cabinet
  alias: '[Push Notify (Детская)] - Включить увлажнитель'
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: HUMIDIFIERON
  action:
    - service: humidifier.turn_on
      target:
        entity_id: 
          - humidifier.deerma_jsq5_humidifier
    
    - delay: '00:00:03'
    
    - service: humidifier.set_mode
      data:
        mode: Humidity
      target:
        entity_id:
          - humidifier.deerma_jsq5_humidifier
    
    - delay: '00:00:03'
    
    - service: humidifier.set_humidity
      data:
        humidity: 40
      target:
        entity_id:
          - humidifier.deerma_jsq5_humidifier
          
- id: push_notify_humidifier_cabinet_1h
  alias: '[Push Notify (Детская)] - Включить увлажнитель на 1 час'
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: HUMIDIFIERON1H
  action:
    - service: humidifier.turn_on
      target:
        entity_id: 
          - humidifier.deerma_jsq5_humidifier
    
    - delay: '00:00:03'
    
    - service: humidifier.set_mode
      data:
        mode: Humidity
      target:
        entity_id:
          - humidifier.deerma_jsq5_humidifier
    
    - delay: '00:00:03'
    
    - service: humidifier.set_humidity
      data:
        humidity: 40
      target:
        entity_id:
          - humidifier.deerma_jsq5_humidifier
          
    - delay: '01:00:00'
    
    - service: humidifier.turn_off
      target:
        entity_id: 
          - humidifier.deerma_jsq5_humidifier

- id: push_notify_ac_fan_cabinet  
  alias: '[Push Notify (Детская)] - Включить кондиционер (вентилятор)'
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: ACONFAN
  action:
    - service: climate.set_hvac_mode
      data:
        hvac_mode: fan
      target:
        entity_id:
          - climate.cabinet_midea_ac
          
          
- id: push_notify_ac_fan_cabinet_1h  
  alias: '[Push Notify (Детская)] - Включить кондиционер на час (вентилятор)'
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: ACONFANON1H
  action:
    - service: climate.set_hvac_mode
      data:
        hvac_mode: fan
      target:
        entity_id:
          - climate.cabinet_midea_ac
  
    - delay: '01:00:00'
    
    - service: climate.turn_off
      target:
        entity_id:
          - climate.cabinet_midea_ac