- platform: template
  sensors:
    datchik_temperatury_zal_availability_problem:
      friendly_name: "Датчик температуры (Зал)_availability_problem"
      icon_template: > 
        {% if is_state('sensor.datchik_temperatury_zal_availability', 'offline') %}
          mdi:car-brake-alert 
        {% else %}
          mdi:car-brake-worn-linings
        {% endif %}
      value_template: >
        {% if is_state('sensor.datchik_temperatury_zal_availability', 'offline') %}
          ON
        {% else %}
          OFF
        {% endif %}
      device_class: "problem"