- platform: template
  sensors:
    cabinet_ac_switch_availability_problem:
      friendly_name: "Розетка Кондиционер (Детская)_availability_problem"
      icon_template: > 
        {% if is_state('sensor.cabinet_ac_switch_availability', 'offline') %}
          mdi:car-brake-alert 
        {% else %}
          mdi:car-brake-worn-linings
        {% endif %}
      value_template: >
        {% if is_state('sensor.cabinet_ac_switch_availability', 'offline') %}
          ON
        {% else %}
          OFF
        {% endif %}
      device_class: "problem"