- platform: template
  sensors:
    pravoe_okno_bar_availability_problem:
      friendly_name: "Правое окно (Бар)_availability_problem"
      icon_template: > 
        {% if is_state('sensor.pravoe_okno_bar_availability', 'offline') %}
          mdi:car-brake-alert 
        {% else %}
          mdi:car-brake-worn-linings
        {% endif %}
      value_template: >
        {% if is_state('sensor.pravoe_okno_bar_availability', 'offline') %}
          ON
        {% else %}
          OFF
        {% endif %}
      device_class: "problem"

####################

- platform: template
  sensors:
    aqara_bar_left_window_availability_problem:
      friendly_name: "Левое окно (Бар)_availability_problem"
      icon_template: > 
        {% if is_state('sensor.aqara_bar_left_window_availability', 'offline') %}
          mdi:car-brake-alert 
        {% else %}
          mdi:car-brake-worn-linings
        {% endif %}
      value_template: >
        {% if is_state('sensor.aqara_bar_left_window_availability', 'offline') %}
          ON
        {% else %}
          OFF
        {% endif %}
      device_class: "problem"
  
####################
 
- platform: template
  sensors:
    levoe_okno_fortochka_bar_availability_problem:
      friendly_name: "Левое окно форточка (Бар)_availability_problem"
      icon_template: > 
        {% if is_state('sensor.levoe_okno_fortochka_bar_availability', 'offline') %}
          mdi:car-brake-alert 
        {% else %}
          mdi:car-brake-worn-linings
        {% endif %}
      value_template: >
        {% if is_state('sensor.levoe_okno_fortochka_bar_availability', 'offline') %}
          ON
        {% else %}
          OFF
        {% endif %}
      device_class: "problem"