- platform: template
  sensors:
    aqara_bar_big_window_contact_availability_problem:
      friendly_name: "Правое окно (Бар)_availability_problem"
      icon_template: > 
        {% if is_state('sensor.aqara_bar_big_window_contact', 'offline') %}
          mdi:car-brake-alert 
        {% else %}
          mdi:car-brake-worn-linings
        {% endif %}
      value_template: >
        {% if is_state('sensor.aqara_bar_big_window_contact', 'offline') %}
          ON
        {% else %}
          OFF
        {% endif %}
      device_class: "problem"
      
- platform: "mqtt"
  unique_id: aqara_bar_big_window_contact
  name: Правое окно (Бар)
  state_topic: "zigbee2mqtt/bar_big_window"
  availability_topic: "zigbee2mqtt/bar_big_window/availability"
  value_template: "{{ value_json.contact }}"
  payload_on: false
  payload_off: true
  device_class: "window"

#########################

- platform: template
  sensors:
    aqara_bar_left_window_availability_problem:
      friendly_name: "Левое окно (Бар)_availability_problem"
      icon_template: > 
        {% if is_state('sensor.aqara_bar_left_window_availability', 'offline') %}
          mdi:car-brake-alert 
        {% else %}
          mdi:car-brake-worn-linings
        {% endif %}
      value_template: >
        {% if is_state('sensor.aqara_bar_left_window_availability', 'offline') %}
          ON
        {% else %}
          OFF
        {% endif %}
      device_class: "problem"
      
- platform: "mqtt"
  unique_id: aqara_bar_left_window_contact
  name: Левое окно (Бар)
  state_topic: "zigbee2mqtt/bar_left_window"
  availability_topic: "zigbee2mqtt/bar_left_window/availability"
  value_template: "{{ value_json.contact }}"
  payload_on: false
  payload_off: true
  device_class: "window"
  
####################
 
- platform: template
  sensors:
    aqara_bar_small_window_availability_problem:
      friendly_name: "Левое окно форточка (Бар)_availability_problem"
      icon_template: > 
        {% if is_state('sensor.aqara_bar_small_window_availability', 'offline') %}
          mdi:car-brake-alert 
        {% else %}
          mdi:car-brake-worn-linings
        {% endif %}
      value_template: >
        {% if is_state('sensor.aqara_bar_small_window_availability', 'offline') %}
          ON
        {% else %}
          OFF
        {% endif %}
      device_class: "problem"
      
- platform: "mqtt"
  unique_id: aqara_bar_small_window_contact
  name: Левое окно форточка (Бар)
  state_topic: "zigbee2mqtt/bar_small_window"
  availability_topic: "zigbee2mqtt/bar_small_window/availability"
  value_template: "{{ value_json.contact }}"
  payload_on: false
  payload_off: true
  device_class: "window"