- platform: template
  sensors:
    bedroom_rail_lamps_availability_problem:
      friendly_name: "Трекинговый свет (Спальня)_availability_problem"
      icon_template: > 
        {% if is_state('sensor.bedroom_rail_lamps_availability', 'offline') %}
          mdi:car-brake-alert 
        {% else %}
          mdi:car-brake-worn-linings
        {% endif %}
      value_template: >
        {% if is_state('sensor.bedroom_rail_lamps_availability', 'offline') %}
          ON
        {% else %}
          OFF
        {% endif %}
      device_class: "problem"