- platform: template
  sensors:
    aqara_bedroom_leak_availability_problem:
      friendly_name: "Датчик утечки воды (Спальня)_availability_problem"
      icon_template: > 
        {% if is_state('sensor.aqara_bedroom_leak_availability', 'offline') %}
          mdi:car-brake-alert 
        {% else %}
          mdi:car-brake-worn-linings
        {% endif %}
      value_template: >
        {% if is_state('sensor.aqara_bedroom_leak_availability', 'offline') %}
          ON
        {% else %}
          OFF
        {% endif %}
      device_class: "problem"

- platform: "mqtt"
  unique_id: aqara_bedroom_leak_water_leak
  name: "! Датчик утечки воды (Спальня)"
  state_topic: "zigbee2mqtt/bedroom_leak"
  availability_topic: "zigbee2mqtt/bedroom_leak/availability"
  value_template: "{{ value_json.water_leak }}"
  payload_on: true
  payload_off: false
  device_class: "moisture"

- platform: "mqtt"
  unique_id: aqara_bedroom_leak_battery_low
  name: Датчик утечки воды (Спальня)_батарейка_низкая
  state_topic: "zigbee2mqtt/bedroom_leak"
  availability_topic: "zigbee2mqtt/bedroom_leak/availability"
  value_template: "{{ value_json.battery_low }}"
  payload_on: true
  payload_off: false
  device_class: "battery"

- platform: "mqtt"
  unique_id: aqara_bedroom_leak_tamper
  name: Датчик утечки воды (Спальня)_тампер
  state_topic: "zigbee2mqtt/bedroom_leak"
  availability_topic: "zigbee2mqtt/bedroom_leak/availability"
  value_template: "{{ value_json.tamper }}"
  payload_on: true
  payload_off: false