- id: '1620814583979'
  alias: Nagging Alerting Notification Automation
  description: ''
  use_blueprint:
    path: pavax/nagging_alert_notification.yaml
    input:
      condition_entity_state: 'on'
      sensor_entity: binary_sensor.aqara_bathroom_leak_water_leak
      alert_action:
      - service: notify.notify_vf_telegram
        data:
          message: Обнаружена утечка воды в ванной
      resolved_action:
      - service: notify.notify_vf_telegram
        data:
          message: Утечка воды в ванной устранена
      dismiss_entity: binary_sensor.aqara_bathroom_leak_water_leak
      notify_device: 30b022147fcf5c2a3d629fb09d20ede0
