- platform: mqtt
  name: "Свет (Ванная)"
  unique_id: bath_main_lamp
  icon: mdi:led-variant-on
  command_topic: "bath/cmnd/sonoff_light/power"
  state_topic: "bath/stat/sonoff_light/RESULT"
  state_value_template: "{{ value_json.POWER }}"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: false
  
####################  

- platform: mqtt
  name: "Подсветка (Ванная)"
  unique_id: bathroom_underlight
  icon: mdi:led-strip
  command_topic: "bath/cmnd/sonoff_switch_underlight/power"
  state_topic: "bath/stat/sonoff_switch_underlight/RESULT"
  state_value_template: "{{ value_json.POWER }}"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false