- alias: "[Подсветка (Кухня)] - Переключать состояние Yeelight на кухне через MQTT"
  id: toggle_kitchen_yeelight_underlight
  trigger:
    - platform: mqtt
      topic: "kitchen/cmnd/yeelight/power2"
      # Optional
      payload: "TOGGLE"
      encoding: "utf-8"
  action:
     - service: light.toggle
       entity_id: light.yeelight_strip6_0x12ed5ce2
     - delay: 0.5
     - service: mqtt.publish
       data:
         topic: "kitchen/stat/yeelight/RESULT"
         retain: false
         payload: "{\"POWER2\":\"{{ states('light.yeelight_strip6_0x12ed5ce2') }}\"}"