- alias: "[Подсветка (Кухня)] - Переключать состояние Yeelight на кухне через MQTT"
  id: toggle_kitchen_yeelight_underlight
  trigger:
    - platform: mqtt
      topic: "kitchen/cmnd/yeelight/power2"
      # Optional
      payload: "TOGGLE"
      encoding: "utf-8"
  action:
     - service: light.toggle
       entity_id: light.kitchen_underlight
     - delay: 0.5
     - service: mqtt.publish
       data:
         topic: "kitchen/stat/yeelight/RESULT"
         retain: false
         payload: "{\"POWER2\":\"{{ states('light.kitchen_underlight') }}\"}"


       
- alias: "[Подсветка (Кухня)] - Включать Yeelight на кухне через MQTT"
  trigger:
    - platform: mqtt
      topic: "kitchen/cmnd/yeelight/power2"
      # Optional
      payload: "ON"
      encoding: "utf-8"
  action:
     - service: light.turn_on
       entity_id: light.kitchen_underlight
     - delay: 0.5
     - service: mqtt.publish
       data:
         topic: "kitchen/stat/yeelight/RESULT"
         retain: false
         payload: "{\"POWER2\":\"{{ states('light.kitchen_underlight') }}\"}"
         
- alias: "[Подсветка (Кухня)] - Выключать Yeelight на кухне через MQTT"
  trigger:
    - platform: mqtt
      topic: "kitchen/cmnd/yeelight/power2"
      # Optional
      payload: "OFF"
      encoding: "utf-8"
  action:
     - service: light.turn_off
       entity_id: light.kitchen_underlight
     - delay: 2
     - service: mqtt.publish
       data:
         topic: "kitchen/stat/yeelight/RESULT"
         retain: false
         payload: "{\"POWER2\":\"{{ states('light.kitchen_underlight') }}\"}"
         
         
         
- alias: "[Подсветка (Кухня)] - Переключать яркость Yeelight на кухне через MQTT"
  id: toggle_kitchen_yeelight_underlight_brightness
  trigger:
    - platform: mqtt
      topic: "kitchen/cmnd/yeelight/dim2"
      # Optional
      payload: "TOGGLE"
      encoding: "utf-8"
  action:
    - service: mqtt.publish
      data_template:
        topic: "kitchen/stat/yeelight/brightness2"
        retain: false
        payload_template: >
          {% if states('sensor.kitchen_underlight_brightness')|int > 80 %}        
            30
          {% elif states('sensor.kitchen_underlight_brightness')|int <= 80 %}
            {{ states('sensor.kitchen_underlight_brightness')|int + 30 }}            
          {%- else -%}
            100
          {%- endif %}
    - service: yeelight.set_color_temp_scene
      data_template:
        entity_id: light.kitchen_underlight
        kelvin: > 
          {% if is_state('sensor.kitchen_underlight_color_temp',"unknown") %} 
            6500
          {%- else -%}
            {{ states('sensor.kitchen_underlight_color_temp')|int }}
          {%- endif %}
        brightness: >
          {% if is_state('sensor.kitchen_underlight_brightness',"unknown") %}
            100
          {%- else -%}
            {{ states('sensor.kitchen_underlight_brightness')|int }}
          {%- endif %}
    - delay: 0.5

- alias: "[Подсветка (Кухня)] - Переключать цвет Yeelight на кухне через MQTT"
  id: toggle_kitchen_yeelight_underlight_color_temp
  trigger:
    - platform: mqtt
      topic: "kitchen/cmnd/yeelight/color2"
      # Optional
      payload: "TOGGLE"
      encoding: "utf-8"
  action:
    - service: mqtt.publish
      data_template:
        topic: "kitchen/stat/yeelight/color_temp2"
        retain: false
        payload_template: >
          {% if states('sensor.kitchen_underlight_color_temp')|int > 6000 %}        
            2000
          {% elif states('sensor.kitchen_underlight_color_temp')|int <= 6000 %}
            {{ states('sensor.kitchen_underlight_color_temp')|int + 500 }}            
          {%- else -%}
            6500
          {%- endif %}
    - service: yeelight.set_color_temp_scene
      data_template:
        entity_id: light.kitchen_underlight
        kelvin: > 
          {% if is_state('sensor.kitchen_underlight_color_temp',"unknown") %} 
            6500
          {%- else -%}
            {{ states('sensor.kitchen_underlight_color_temp')|int }}
          {%- endif %}
        brightness: >
          {% if is_state('sensor.kitchen_underlight_brightness',"unknown") %}
            100
          {%- else -%}
            {{ states('sensor.kitchen_underlight_brightness')|int }}
          {%- endif %}
    - delay: 0.5