- alias: "[Основной свет (Кухня)] - Переключать состояние Yeelight на кухне через MQTT"
  id: toggle_kitchen_yeelight
  trigger:
    - platform: mqtt
      topic: "kitchen/cmnd/yeelight/power"
      # Optional
      payload: "TOGGLE"
      encoding: "utf-8"
  action:
     - service: light.toggle
       entity_id: light.yeelight_ceila_0x1a5b20e7
     - delay: 0.5
     - service: mqtt.publish
       data:
         topic: "kitchen/stat/yeelight/RESULT"
         retain: false
         payload: "{\"POWER\":\"{{ states('light.yeelight_ceila_0x1a5b20e7') }}\"}"
    
- alias: "[Основной свет (Кухня)] - Переключать яркость Yeelight на кухне через MQTT"
  id: toggle_kitchen_yeelight_brightness
  trigger:
    - platform: mqtt
      topic: "kitchen/cmnd/yeelight/dim"
      # Optional
      payload: "TOGGLE"
      encoding: "utf-8"
  action:
    - service: light.turn_on
      entity_id: light.yeelight_ceila_0x1a5b20e7
      data_template:
        brightness: >
          {% set step_size = 55 %}
          {% if (state_attr('light.yeelight_ceila_0x1a5b20e7', 'brightness') != None)%}
            {% set current_brightness = (state_attr('light.yeelight_ceila_0x1a5b20e7', 'brightness') | int) %}
          {% else %}
            {% set current_brightness = 0 %}
          {% endif %}
          {% set new_brightness = current_brightness | int + step_size %}
          {% if new_brightness > 255 %}
            0
          {% else %}
            {{ new_brightness }}
          {% endif %}