- alias: "[Основной свет (Спальня)] - Переключать состояние Yeelight в спальне через MQTT"
  id: toggle_bedroom_yeelight
  trigger:
    - platform: mqtt
      topic: "zigbee2mqtt/bedroom_switch/action"
      # Optional
      payload: "button_1_single"
      encoding: "utf-8"
  action:
     - service: light.toggle
       entity_id: light.yeelight_ceiling14_0x12ada382
     - delay: 0.5
     - service: mqtt.publish
       data:
         topic: "bedroom/stat/yeelight/RESULT"
         retain: false
         payload: "{\"POWER\":\"{{ states('light.yeelight_ceiling14_0x12ada382') }}\"}"
       
         
- alias: "[Основной свет (Спальня)] - Переключать яркость Yeelight в спальне через MQTT"
  id: toggle_bedroom_yeelight_brightness
  trigger:
    - platform: mqtt
      topic: "zigbee2mqtt/bedroom_switch/action"
      # Optional
      payload: "button_1_double"
      encoding: "utf-8"
  action:
    - service: light.turn_on
      entity_id: light.yeelight_ceiling14_0x12ada382
      data_template:
        brightness: >
          {% set step_size = 55 %}
          {% if (state_attr('light.yeelight_ceiling14_0x12ada382', 'brightness') != None)%}
            {% set current_brightness = (state_attr('light.yeelight_ceiling14_0x12ada382', 'brightness') | int) %}
          {% else %}
            {% set current_brightness = 0 %}
          {% endif %}
          {% set new_brightness = current_brightness | int + step_size %}
          {% if new_brightness > 255 %}
            0
          {% else %}
            {{ new_brightness }}
          {% endif %}