- alias: "[Основной свет (Спальня)] - Переключать состояние Yeelight в спальне через MQTT"
  id: toggle_bedroom_yeelight
  trigger:
    - platform: mqtt
      topic: "zigbee2mqtt/bedroom_switch/action"
      # Optional
      payload: "button_1_single"
      encoding: "utf-8"
  action:
     - service: light.toggle
       entity_id: light.bedroom_main_lamp
     - delay: 0.5
     - service: mqtt.publish
       data:
         topic: "bedroom/stat/yeelight/RESULT"
         retain: false
         payload: "{\"POWER\":\"{{ states('light.bedroom_main_lamp') }}\"}"
       
- alias: "[Основной свет (Спальня)] - Включать Yeelight в спальне через MQTT"
  trigger:
    - platform: mqtt
      topic: "bedroom/cmnd/yeelight/power"
      # Optional
      payload: "ON"
      encoding: "utf-8"
  action:
     - service: light.turn_on
       entity_id: light.bedroom_main_lamp
     - delay: 0.5
     - service: mqtt.publish
       data:
         topic: "bedroom/stat/yeelight/RESULT"
         retain: false
         payload: "{\"POWER\":\"{{ states('light.bedroom_main_lamp') }}\"}"
         
- alias: "[Основной свет (Спальня)] - Выключать Yeelight в спальне через MQTT"
  trigger:
    - platform: mqtt
      topic: "bedroom/cmnd/yeelight/power"
      # Optional
      payload: "OFF"
      encoding: "utf-8"
  action:
     - service: light.turn_off
       entity_id: light.bedroom_main_lamp
     - delay: 2
     - service: mqtt.publish
       data:
         topic: "bedroom/stat/yeelight/RESULT"
         retain: false
         payload: "{\"POWER\":\"{{ states('light.bedroom_main_lamp') }}\"}"
         
- alias: "[Основной свет (Спальня)] - Переключать яркость Yeelight в спальне через MQTT"
  id: toggle_bedroom_yeelight_brightness
  trigger:
    - platform: mqtt
      topic: "zigbee2mqtt/bedroom_switch/action"
      # Optional
      payload: "button_1_double"
      encoding: "utf-8"
  action:
    - service: mqtt.publish
      data_template:
        topic: "bedroom/stat/yeelight/brightness"
        retain: false
        payload_template: >
          {% if states('sensor.bedroom_main_lamp_brightness')|int >=99 %}        
            0
          {% elif states('sensor.bedroom_main_lamp_brightness')|int < 99 %}
            {{ states('sensor.bedroom_main_lamp_brightness')|int + 33 }}            
          {%- else -%}
            100
          {%- endif %}
    - service: yeelight.set_color_temp_scene
      data_template:
        entity_id: light.bedroom_main_lamp
        kelvin: > 
          {% if is_state('sensor.bedroom_main_lamp_color_temp',"unknown") %} 
            6500
          {%- else -%}
            {{ states('sensor.bedroom_main_lamp_color_temp')|int }}
          {%- endif %}
        brightness: >
          {% if is_state('sensor.bedroom_main_lamp_brightness',"unknown") %}
            100
          {%- else -%}
            {{ states('sensor.bedroom_main_lamp_brightness')|int }}
          {%- endif %}
    - delay: 0.5

- alias: "[Основной свет (Спальня)] - Переключать цвет Yeelight в спальне через MQTT"
  id: toggle_bedroom_yeelight_color_temp
  trigger:
    - platform: mqtt
      topic: "zigbee2mqtt/bedroom_switch/action"
      # Optional
      payload: "button_1_triple"
      encoding: "utf-8"
  action:
    - service: mqtt.publish
      data_template:
        topic: "bedroom/stat/yeelight/color_temp"
        retain: false
        payload_template: >
          {% if states('sensor.bedroom_main_lamp_color_temp')|int > 6000 %}        
            2000
          {% elif states('sensor.bedroom_main_lamp_color_temp')|int < 4000 %}
            {{ states('sensor.bedroom_main_lamp_color_temp')|int + 2000 }}            
          {%- else -%}
            6500
          {%- endif %}
    - service: yeelight.set_color_temp_scene
      data_template:
        entity_id: light.bedroom_main_lamp
        kelvin: > 
          {% if is_state('sensor.bedroom_main_lamp_color_temp',"unknown") %} 
            6500
          {%- else -%}
            {{ states('sensor.bedroom_main_lamp_color_temp')|int }}
          {%- endif %}
        brightness: >
          {% if is_state('sensor.bedroom_main_lamp_brightness',"unknown") %}
            100
          {%- else -%}
            {{ states('sensor.bedroom_main_lamp_brightness')|int }}
          {%- endif %}
    - delay: 0.5