- alias: "[Подсветка (Спальня)] - Переключать состояние подсветки в спальне через MQTT"
  id: toggle_bedroom_underlight
  trigger:
    - platform: mqtt
      topic: "zigbee2mqtt/bedroom_switch/action"
      # Optional
      payload: "button_2_double"
      encoding: "utf-8"
  action:
     - service: light.toggle
       entity_id: light.bedroom_underlight
     - delay: 0.5
     - service: mqtt.publish
       data:
         topic: "bedroom/stat/yeelight/RESULT2"
         retain: false
         payload: "{\"POWER\":\"{{ states('light.bedroom_underlight') }}\"}"
         
