- platform: group
  unique_id: bar_tsvetnye
  name: "Бар цветные"
  entities:
    - light.yeelight_mono4_0x10175539
    - light.yeelight_mono4_0x10176043
    - light.yeelight_mono4_0x1017ad1a

- platform: group
  unique_id: zal_tsvetnye
  name: "Зал цветные"
  entities:
    - light.yeelight_colorb_0x1b2e2ace
    - light.yeelight_colorb_0x1b11c344
    - light.yeelight_colorb_0x1c0604de
    - light.yeelight_colorb_0x1c0565ae
    - light.yeelight_colorb_0x1c05614f

- platform: group
  unique_id: zal_tsvetnye_malenkie
  name: "Зал цветные маленькие"
  entities:
    - light.yeelight_colorb_0x1b2e2ace
    - light.yeelight_colorb_0x1b11c344
    - light.yeelight_colorb_0x1c0604de
    - light.yeelight_colorb_0x1c0565ae
    - light.yeelight_colorb_0x1c05614f


- platform: group
  unique_id: tsvetnye_lenty
  name: "Цветные ленты"
  entities:
    - light.yeelight_strip6_0x12ed5ce2
    - light.yeelight_stripa_0x19db0b1e
