- platform: group
  unique_id: bar_tsvetnye
  name: "Бар цветные"
  entities:
    - light.philips_cbulb_3896_light
    - light.philips_cbulb_0c10_light
    - light.philips_cbulb_734f_light

- platform: group
  unique_id: zal_tsvetnye
  name: "Зал цветные"
  entities:
    - light.philips_cbulb_338e_light
    - light.philips_cbulb_f841_light
    - light.philips_cbulb_b87d_light
    - light.philips_cbulb_c7d3_light

- platform: group
  unique_id: zal_tsvetnye_malenkie
  name: "Зал цветные маленькие"
  entities:
    - light.philips_cbulb_4b48_light
    - light.philips_cbulb_2872_light

- platform: group
  unique_id: tsvetnye_lenty
  name: "Цветные ленты"
  entities:
    - light.yeelight_strip6_0x12ed5ce2