- platform: "mqtt"
  unique_id: aqara_kitchen_button_availability
  name: Кнопка подсветки (Кухня)_availability
  state_topic: "zigbee2mqtt/kitchen_underlight_button/availability"
  
- platform: "mqtt"
  unique_id: aqara_kitchen_button_click
  name: Кнопка подсветки (Кухня)_click
  state_topic: "zigbee2mqtt/kitchen_underlight_button"
  availability_topic: "zigbee2mqtt/kitchen_underlight_button/availability"
  icon: "mdi:toggle-switch"
  value_template: "{{ value_json.click }}"

- platform: "mqtt"
  unique_id: aqara_kitchen_button_battery
  name: Кнопка подсветки (Кухня)_battery
  state_topic: "zigbee2mqtt/kitchen_underlight_button"
  availability_topic: "zigbee2mqtt/kitchen_underlight_button/availability"
  value_template: "{{ value_json.battery }}"
  unit_of_measurement: "%"
  device_class: "battery"

- platform: "mqtt"
  unique_id: aqara_kitchen_button_action
  name: Кнопка подсветки (Кухня)_action
  state_topic: "zigbee2mqtt/kitchen_underlight_button"
  availability_topic: "zigbee2mqtt/kitchen_underlight_button/availability"
  value_template: "{{ value_json.action }}"
  icon: "mdi:gesture-double-tap"

# - platform: "mqtt"
#   unique_id: aqara_kitchen_button_voltage
#   name: Кнопка подсветки (Кухня)_voltage
#   state_topic: "zigbee2mqtt/kitchen_underlight_button"
#   availability_topic: "zigbee2mqtt/kitchen_underlight_button/availability"
#   value_template: "{{ value_json.voltage }}"
#   unit_of_measurement: "mV"
#   device_class: "voltage"

# - platform: "mqtt"
#   unique_id: aqara_kitchen_button_signal
#   name: Кнопка подсветки (Кухня)_signal
#   state_topic: "zigbee2mqtt/kitchen_underlight_button"
#   availability_topic: "zigbee2mqtt/kitchen_underlight_button/availability"
#   value_template: "{{ value_json.linkquality }}"
#   unit_of_measurement: "lqi"
#   icon: "mdi:signal"