- platform: "mqtt"
  unique_id: kitchen_gas_sensor_availability
  name: Датчик газа (Кухня)_availability
  state_topic: "zigbee2mqtt/kitchen_gas_sensor/availability"
    
# - platform: "mqtt"
#   unique_id: kitchen_gas_sensor_signal
#   name: Датчик утечки газа (Кухня_полоток)_signal
#   state_topic: "zigbee2mqtt/kitchen_gas_sensor"
#   availability_topic: "zigbee2mqtt/kitchen_gas_sensor/availability"
#   value_template: "{{ value_json.linkquality }}"
#   unit_of_measurement: "lqi"
#   icon: "mdi:signal"