- alias: "[ OCCUPANCY ] - Включать свет по датчику движения (Спальня)"
  id: bedroom_occupancy_light
  trigger:
    - platform: state
      entity_id: group.bedroom_motion_sensors
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.auto_lights_motion
      state: "on"
    - condition: state
      entity_id: sun.sun
      state: "below_horizon"
    # - condition: state
    #   entity_id: group.iphone_focus
    #   state: "on"
  action:
    - choose:
      - conditions:
          - condition: state
            entity_id: group.bedroom_motion_sensors
            state: 'on'
          - condition: state
            entity_id: group.my_device_trackers
            state: home
          - condition: state
            entity_id: group.bedroom_lights
            state: 'off'
        sequence:
          - service: light.turn_on
            entity_id: light.yeelight_stripa_0x19db0b1e
            data_template:
              color_name: >
                {{states('input_select.cicle_light_color')}}
              transition: 2
          - service: automation.turn_on
            target:
              entity_id: automation.cicle_light_color_change

      - conditions:
          - condition: state
            entity_id: light.yeelight_stripa_0x19db0b1e
            state: 'on'  
        sequence:
          - service: light.turn_off
            entity_id: light.yeelight_stripa_0x19db0b1e
          - service: automation.turn_off
            target:
              entity_id: automation.cicle_light_color_change


- alias: "[ OCCUPANCY ] - Выключать свет по датчику движения 5 минут (Спальня)"
  id: bedroom_occupancy_light_off_5min
  trigger:
    - platform: state
      entity_id: group.bedroom_motion_sensors
      to: 'off'
      for: 00:05:00
  condition:
    - condition: state
      entity_id: input_boolean.auto_lights_motion
      state: "on"
    - condition: state
      entity_id: sun.sun
      state: "below_horizon"
  action:
    - choose:
      - conditions:
          - condition: state
            entity_id: group.bedroom_motion_sensors
            state: 'off'
          - condition: state
            entity_id: light.yeelight_stripa_0x19db0b1e
            state: 'on'
        sequence:
          - service: light.turn_off
            data:
              transition: 0
            target:
              entity_id: light.yeelight_stripa_0x19db0b1e


- alias: "[ OCCUPANCY ] - Выключать свет по датчику движения 30 минут (Спальня)"
  id: bedroom_occupancy_light_off_30min
  trigger:
    - platform: state
      entity_id: group.bedroom_motion_sensors
      to: 'off'
      for: 00:30:00
  action:
    - choose:
      - conditions:
          - condition: state
            entity_id: group.bedroom_motion_sensors
            state: 'off'
          - condition: state
            entity_id: group.bedroom_lights
            state: 'on'
        sequence:
          - service: light.turn_off
            target:
              entity_id: group.bedroom_lights
          - delay: 00:00:05
          - service: light.turn_off
            target:
              entity_id: light.yeelight_stripa_0x19db0b1e