- platform: template
  sensors:
    ikea_blinds_availability_problem:
      friendly_name: "Жалюзи (Бар)_availability_problem"
      icon_template: > 
        {% if is_state('sensor.ikea_blinds_availability', 'offline') %}
          mdi:car-brake-alert 
        {% else %}
          mdi:car-brake-worn-linings
        {% endif %}
      value_template: >
        {% if is_state('sensor.ikea_blinds_availability', 'offline') %}
          ON
        {% else %}
          OFF
        {% endif %}
      device_class: "problem"