- platform: template
  sensors:
    ikea_repeater_availability_problem:
      friendly_name: "IKEA Рипитер (Общее)_availability_problem"
      icon_template: > 
        {% if is_state('sensor.ikea_repeater_availability', 'offline') %}
          mdi:car-brake-alert 
        {% else %}
          mdi:car-brake-worn-linings
        {% endif %}
      value_template: >
        {% if is_state('sensor.ikea_repeater_availability', 'offline') %}
          ON
        {% else %}
          OFF
        {% endif %}
      device_class: "problem"