- alias: "[Кнопка подсветки (Ванная)] - Переключать Ванную подсветку по нажатию на Aqara Button"
  id: toggle_podsvetka_vannaia
  trigger:
    - platform: mqtt
      topic: "zigbee2mqtt/bathroom_underlight_button/action"
      # Optional
      #payload: "single"
      encoding: "utf-8"
  mode: single
  action:
     - service: light.toggle
       entity_id: light.podsvetka_vannaia
     - delay: '00:00:02'