- alias: "[Основной свет (Детская)] - Переключать состояние Yeelight в детской через MQTT"
  id: toggle_cabinet_yeelight
  trigger:
    - platform: mqtt
      topic: "cabinet/cmnd/yeelight/power"
      # Optional
      payload: "TOGGLE"
      encoding: "utf-8"
  action:
     - service: light.toggle
       entity_id: light.cabinet_main_lamp
     - delay: 0.5
     - service: mqtt.publish
       data:
         topic: "cabinet/stat/yeelight/RESULT"
         retain: false
         payload: "{\"POWER\":\"{{ states('light.cabinet_main_lamp') }}\"}"
       
- alias: "[Основной свет (Детская)] - Включать Yeelight в детской через MQTT"
  trigger:
    - platform: mqtt
      topic: "cabinet/cmnd/yeelight/power"
      # Optional
      payload: "ON"
      encoding: "utf-8"
  action:
     - service: light.turn_on
       entity_id: light.cabinet_main_lamp
     - delay: 0.5
     - service: mqtt.publish
       data:
         topic: "cabinet/stat/yeelight/RESULT"
         retain: false
         payload: "{\"POWER\":\"{{ states('light.cabinet_main_lamp') }}\"}"
         
- alias: "[Основной свет (Детская)] - Выключать Yeelight в детской через MQTT"
  trigger:
    - platform: mqtt
      topic: "cabinet/cmnd/yeelight/power"
      # Optional
      payload: "OFF"
      encoding: "utf-8"
  action:
     - service: light.turn_off
       entity_id: light.cabinet_main_lamp
     - delay: 2
     - service: mqtt.publish
       data:
         topic: "cabinet/stat/yeelight/RESULT"
         retain: false
         payload: "{\"POWER\":\"{{ states('light.cabinet_main_lamp') }}\"}"
         
- alias: "[Основной свет (Детская)] - Переключать яркость Yeelight в детской через MQTT"
  id: toggle_cabinet_yeelight_brightness
  trigger:
    - platform: mqtt
      topic: "cabinet/cmnd/yeelight/dim"
      # Optional
      payload: "TOGGLE"
      encoding: "utf-8"
  action:
    - service: mqtt.publish
      data_template:
        topic: "cabinet/stat/yeelight/brightness"
        retain: false
        payload_template: >
          {% if states('sensor.cabinet_main_lamp_brightness')|int >= 99 %}        
            0
          {% elif states('sensor.cabinet_main_lamp_brightness')|int < 99 %}
            {{ states('sensor.cabinet_main_lamp_brightness')|int + 33 }}            
          {%- else -%}
            100
          {%- endif %}
    - service: yeelight.set_color_temp_scene
      data_template:
        entity_id: light.cabinet_main_lamp
        kelvin: > 
          {% if is_state('sensor.cabinet_main_lamp_color_temp',"unknown") %} 
            6500
          {%- else -%}
            {{ states('sensor.cabinet_main_lamp_color_temp')|int }}
          {%- endif %}
        brightness: >
          {% if is_state('sensor.cabinet_main_lamp_brightness',"unknown") %}
            100
          {%- else -%}
            {{ states('sensor.cabinet_main_lamp_brightness')|int }}
          {%- endif %}
    - delay: 0.5

- alias: "[Основной свет (Детская)] - Переключать цвет Yeelight в детской через MQTT"
  id: toggle_cabinet_yeelight_color_temp
  trigger:
    - platform: mqtt
      topic: "cabinet/cmnd/yeelight/color"
      # Optional
      payload: "TOGGLE"
      encoding: "utf-8"
  action:
    - service: mqtt.publish
      data_template:
        topic: "cabinet/stat/yeelight/color_temp"
        retain: false
        payload_template: >
          {% if states('sensor.cabinet_main_lamp_color_temp')|int > 6000 %}        
            2000
          {% elif states('sensor.cabinet_main_lamp_color_temp')|int < 4000 %}
            {{ states('sensor.cabinet_main_lamp_color_temp')|int + 2000 }}            
          {%- else -%}
            6500
          {%- endif %}
    - service: yeelight.set_color_temp_scene
      data_template:
        entity_id: light.cabinet_main_lamp
        kelvin: > 
          {% if is_state('sensor.cabinet_main_lamp_color_temp',"unknown") %} 
            6500
          {%- else -%}
            {{ states('sensor.cabinet_main_lamp_color_temp')|int }}
          {%- endif %}
        brightness: >
          {% if is_state('sensor.cabinet_main_lamp_brightness',"unknown") %}
            100
          {%- else -%}
            {{ states('sensor.cabinet_main_lamp_brightness')|int }}
          {%- endif %}
    - delay: 0.5