- alias: "[Кнопка подсветки (Прихожую)] - Переключать Прихожую подсветку по нажатию на Aqara Button"
  id: toggle_podsvetka_prikhozhaia
  trigger:
    - platform: mqtt
      topic: "zigbee2mqtt/hall_underlight_button/action"
      # Optional
      #payload: "single"
      encoding: "utf-8"
  mode: single
  action:
     - service: light.toggle
       entity_id: light.podsvetka_prikhozhaia
     - delay: '00:00:02'