- platform: template
  sensors:
    dver_podezd_availability_problem:
      friendly_name: "Дверь (Подъезд)_availability_problem"
      icon_template: > 
        {% if is_state('sensor.dver_podezd_availability', 'offline') %}
          mdi:car-brake-alert 
        {% else %}
          mdi:car-brake-worn-linings
        {% endif %}
      value_template: >
        {% if is_state('sensor.dver_podezd_availability', 'offline') %}
          ON
        {% else %}
          OFF
        {% endif %}
      device_class: "problem"