- alias: "[Электроэнергия] - Смена тарифа электроэнергии по месяцам"
  initial_state: true
  trigger:
    platform: time
    at: '00:00:01'
  condition:
    condition: template
    value_template: "{{ now().day == 1 }}"
  action:
    - service: utility_meter.next_tariff
      entity_id: 
        - utility_meter.electricity_monthly
        
    - delay: 00:00:05
    
    - service: telegram_bot.send_message
      data:
        title: "<b>Инфомационное сообщение</b>"
        message: >
          Внимание произведена смена подсчета электроэнергии: 
          Активный месяц счетчика: {{ states(utility_meter.electricity_monthly) }}
        target:
          - !secret telegram_id_1
          - !secret telegram_id_2
        disable_notification: false      
   
        
- alias: "[Электроэнергия] - Смена тарифа электроэнергии по годам"
  initial_state: true
  trigger:
    platform: time
    at: '00:05:00'
  condition:
    condition: and
    conditions: 
      - condition: template
        value_template: "{{ now().month == 1 }}" 
      - condition: template
        value_template: "{{ now().day == 1 }}"
  action:
    - service: utility_meter.next_tariff
      entity_id: 
        - utility_meter.electricity_yearly
        
    - delay: 00:00:05
    
    - service: telegram_bot.send_message
      data:
        title: "<b>Инфомационное сообщение</b>"
        message: >
          Внимание произведена смена подсчета электроэнергии: 
          Активный год счетчика: {{ states(utility_meter.electricity_monthly) }}
        target:
          - !secret telegram_id_1
          - !secret telegram_id_2
        disable_notification: false     