- alias: "[Электроэнергия] - Отчет электроэнергии - ежедневный"
  id: utility_meter_energy_daily
  initial_state: on
  trigger:
    platform: time
    at: '23:57:59'
  action:               
          
    - service: telegram_bot.send_message
      data:
        title: "<b>Отчет об электроэнергии</b>"
        message: > 
          Текущая стоимость кВт.ч: <b>{{ states('sensor.electricity_price_current') }}</b> СУМ 

          ------- ТЕКУЩИЙ МЕСЯЦ -------
          
          Использовано <b>{{ states('sensor.elektrichestvo_mesiats') }}</b> кВт
          
          Сумма: <b>{{ states('sensor.electricity_cost_monthly') }}</b> Сум

          ----------- ВЧЕРА -----------

          Использовано <b>{{ states('sensor.pzem04_energy_yesterday') }}</b> кВт
          
          Сумма: <b>{{ states('sensor.house_cost_yesterday') }}</b> Сум

          ---------- СЕГОДНЯ ----------

          Использовано <b>{{ states('sensor.pzem04_energy_today') }}</b> кВт 
          
          Кондиционер в детской: <b>{{ states('sensor.ac_cost_daily') }}</b> Сум
          
          Кондиционер в спальне: <b>{{ states('sensor.ac_bedroom_cost_daily') }}</b> Сум
          
          Полотенцесушитель: <b>{{ states('sensor.bath_radiator_cost_daily') }}</b> Сум
          
          Стиральная машинка: <b>{{ states('sensor.washer_cost_daily') }}</b> Сум

          Xbox и телевизор: <b>{{ states('sensor.livingroom_cost_daily')}}</b> Сум

          Серверная комната: <b>{{ states('sensor.server_cost_daily')}}</b> Сум

          Сумма: <b>{{ states('sensor.house_cost_daily') }}</b> Сум


        target:
          - !secret telegram_id_1
          - !secret telegram_id_2
        disable_notification: false  
        
    
        
