- platform: template
  sensors:
    rozetka_polotentsesushitel_vannaia_availability_problem:
      friendly_name: "Розетка Полотенцесушитель (Ванная)_availability_problem"
      icon_template: > 
        {% if is_state('sensor.rozetka_polotentsesushitel_vannaia_availability', 'offline') %}
          mdi:car-brake-alert 
        {% else %}
          mdi:car-brake-worn-linings
        {% endif %}
      value_template: >
        {% if is_state('sensor.rozetka_polotentsesushitel_vannaia_availability', 'offline') %}
          ON
        {% else %}
          OFF
        {% endif %}
      device_class: "problem"
 
 ####################
 
    rozetka_stiralnaia_mashina_vannaia_availability_problem:
      friendly_name: "Розетка Стиральная машина (Ванная)_availability_problem"
      icon_template: > 
        {% if is_state('sensor.rozetka_stiralnaia_mashina_vannaia_availability', 'offline') %}
          mdi:car-brake-alert 
        {% else %}
          mdi:car-brake-worn-linings
        {% endif %}
      value_template: >
        {% if is_state('sensor.rozetka_stiralnaia_mashina_vannaia_availability', 'offline') %}
          ON
        {% else %}
          OFF
        {% endif %}
      device_class: "problem"