- alias: "[Кнопка подсветки (Кухня)] - Переключать Кухонную подсветку по нажатию на Aqara Button"
  id: toggle_kitchen_underlight
  trigger:
    - platform: mqtt
      topic: "zigbee2mqtt/kitchen_underlight_button/action"
      # Optional
      payload: "single"
      encoding: "utf-8"
  action:
     - service: light.toggle
       entity_id: light.kitchen_underlight
       
# - alias: "[Кнопка подсветки (Кухня)] - Переключать Яркость подсветки по двойному нажатию на Aqara Button"
  # id: toggle_kitchen_underlight_brightness
  # trigger:
    # - platform: mqtt
      # topic: "zigbee2mqtt/kitchen_underlight_button/action"
      # # Optional
      # payload: "double"
      # encoding: "utf-8"
  # action:
     # - service: light.toggle
       # entity_id: light.kitchen_underlight
       
# - alias: "[Кнопка подсветки (Кухня)] - Переключать Цвет подсветки по тройному нажатию на Aqara Button"
  # id: toggle_kitchen_underlight_color
  # trigger:
    # - platform: mqtt
      # topic: "zigbee2mqtt/kitchen_underlight_button/action"
      # # Optional
      # payload: "double"
      # encoding: "utf-8"
  # action:
     # - service: light.toggle
       # entity_id: light.kitchen_underlight