- alias: "[Кнопка подсветки (Кухня)] - Переключать Кухонную подсветку по нажатию на Aqara Button"
  id: toggle_yeelight_strip6_0x12ed5ce2
  trigger:
    - platform: mqtt
      topic: "zigbee2mqtt/kitchen_underlight_button/action"
      # Optional
      payload: "single"
      encoding: "utf-8"
  action:
     - service: light.toggle
       entity_id: light.yeelight_strip6_0x12ed5ce2