- platform: "mqtt"
  unique_id: aqara_toilet_door_availability
  name: Дверь (Туалет)_availability
  state_topic: "zigbee2mqtt/toilet_door/availability"
  
- platform: "mqtt"
  unique_id: aqara_toilet_door_temperature
  name: Дверь (Туалет)_temperature
  state_topic: "zigbee2mqtt/toilet_door"
  availability_topic: "zigbee2mqtt/toilet_door/availability"
  value_template: "{{ value_json.temperature }}"
  unit_of_measurement: "°C"
  device_class: "temperature"

# - platform: "mqtt"
#   unique_id: aqara_toilet_door_voltage
#   name: Дверь (Туалет)_voltage
#   state_topic: "zigbee2mqtt/toilet_door"
#   availability_topic: "zigbee2mqtt/toilet_door/availability"
#   value_template: "{{ value_json.voltage }}"
#   unit_of_measurement: "mV"
#   device_class: "voltage"

# - platform: "mqtt"
#   unique_id: aqara_toilet_door_signal
#   name: Дверь (Туалет)_signal
#   state_topic: "zigbee2mqtt/toilet_door"
#   availability_topic: "zigbee2mqtt/toilet_door/availability"
#   value_template: "{{ value_json.linkquality }}"
#   unit_of_measurement: "lqi"
#   icon: "mdi:signal"
  
- platform: "mqtt"
  unique_id: aqara_toilet_door_battery
  name: Дверь (Туалет)_battery
  state_topic: "zigbee2mqtt/toilet_door"
  availability_topic: "zigbee2mqtt/toilet_door/availability"
  value_template: "{{ value_json.battery }}"
  unit_of_measurement: "%"
  device_class: "battery"