- alias: "[ Light ] - Переключать цвет кубиком основных лампочек (Зал)"
  id: change_color_in_livingroom_by_cube
  trigger:
    platform: mqtt
    topic: zigbee2mqtt/cube
  condition:
    condition: template
    value_template: '{{ "flip90" == trigger.payload_json.action }}'
  action:
    - entity_id: input_select.cicle_light_color_living_room
      service: input_select.select_next
    
    - data_template:
        color_name: '{{ states(''input_select.cicle_light_color_living_room'') }}'
        entity_id: light.zal_tsvetnye
        transition: 0
      service: light.turn_on

- alias: "[ Light ] - Выключать цвет кубиком основных лампочек (Зал)"
  id: turnoff_light_in_livingroom_by_cube
  trigger:
    platform: mqtt
    topic: zigbee2mqtt/cube
  condition:
    condition: template
    value_template: '{{ "fall" == trigger.payload_json.action }}'
  action:

    - service: light.turn_off
      entity_id: light.zal_tsvetnye

      

- alias: "[ Light ] - Вернуть белый цвет кубиком основных лампочек (Зал)"
  id: change_color_in_livingroom_by_cube_shake
  trigger:
    platform: mqtt
    topic: zigbee2mqtt/cube
  condition:
    condition: template
    value_template: '{{ "shake" == trigger.payload_json.action }}'
  action:    
    - data_template:
        color_name: 'white'
        entity_id: light.zal_tsvetnye
        transition: 0
        brightness_pct: 100
      service: light.turn_on

- alias: "[ Light ] - Яркость основных лампочек кубиком (Зал)"
  id: change_color_in_livingroom_by_cube_rotate 
  trigger:
    platform: mqtt
    topic: zigbee2mqtt/cube
  condition:
    condition: template
    value_template: "{{ trigger.payload_json.action in ['rotate_right', 'rotate_left'] }}"
  action:         
    - service: light.turn_on
      data:
        entity_id: light.zal_tsvetnye
    
    - service: light.turn_on
      data_template:
        entity_id: light.zal_tsvetnye
        brightness: >-
          {% if trigger.payload_json.angle | float > 0 %}
          {{ light.philips_cbulb_338e_light.attributes.light.brightness | int + 20 }}
          {% else %}
          {{ light.philips_cbulb_338e_light.attributes.light.brightness | int - 20 }}
          {% endif %}    

