- platform: "mqtt"
  unique_id: aqara_bedroom_switch_availability
  name: Выключатель (Спальня)_availability
  state_topic: "zigbee2mqtt/bedroom_switch/availability"

- platform: "mqtt"
  unique_id: aqara_bedroom_switch_battery
  name: Выключатель (Спальня)_battery
  state_topic: "zigbee2mqtt/bedroom_switch"
  availability_topic: "zigbee2mqtt/bedroom_switch/availability"
  value_template: "{{ value_json.battery }}"
  unit_of_measurement: "%"
  device_class: "battery"

- platform: "mqtt"
  unique_id: aqara_bedroom_switch_action
  name: Выключатель (Спальня)_action
  state_topic: "zigbee2mqtt/bedroom_switch"
  availability_topic: "zigbee2mqtt/bedroom_switch/availability"
  value_template: "{{ value_json.action }}"
  icon: "mdi:gesture-double-tap"

- platform: "mqtt"
  unique_id: aqara_bedroom_switch_operationmode
  name: Выключатель (Спальня)_operationmode
  state_topic: "zigbee2mqtt/bedroom_switch"
  availability_topic: "zigbee2mqtt/bedroom_switch/availability"
  value_template: "{{ value_json.operation_mode }}"

# - platform: "mqtt"
#   unique_id: aqara_bedroom_switch_signal
#   name: Выключатель (Спальня)_signal
#   state_topic: "zigbee2mqtt/bedroom_switch"
#   availability_topic: "zigbee2mqtt/bedroom_switch/availability"
#   value_template: "{{ value_json.linkquality }}"
#   unit_of_measurement: "lqi"
#   icon: "mdi:signal"