- platform: "mqtt"
  unique_id: ikea_blinds_availability
  name: Жалюзи (Бар)_availability
  state_topic: "zigbee2mqtt/ikea_blinds/availability"

- platform: "mqtt"
  unique_id: ikea_blinds_battery
  name: Жалюзи (Бар)_battery
  state_topic: "zigbee2mqtt/ikea_blinds"
  availability_topic: "zigbee2mqtt/ikea_blinds/availability"
  unit_of_measurement: "%"
  value_template: "{{ value_json.battery }}"
  device_class: "battery"

# - platform: "mqtt"
#   unique_id: ikea_blinds_signal
#   name: Жалюзи (Бар)_signal
#   state_topic: "zigbee2mqtt/ikea_blinds"
#   availability_topic: "zigbee2mqtt/ikea_blinds/availability"
#   unit_of_measurement: "lqi"
#   value_template: "{{ value_json.linkquality }}"
#   icon: "mdi:signal"

# - platform: "mqtt"
#   unique_id: ikea_blinds_update_state
#   name: Жалюзи (Бар)_update_state
#   state_topic: "zigbee2mqtt/ikea_blinds"
#   availability_topic: "zigbee2mqtt/ikea_blinds/availability"
#   icon: "mdi:update"
#   value_template: "{{ value_json['update']['state'] }}"
  
- platform: template
  sensors:
    ikea_blinds_state:
      friendly_name: 'Жалюзи (Бар)_status'
      value_template: >-
        {% set state_status = state_attr('cover.ikea_blinds', 'current_position') | int %}
        {% if state_status > 90 and state_status > 70 %}
          Открыты
        {% elif state_status < 70 and state_status > 40 %}
          Полуоткрыты
        {% else %}
          Закрыты
        {% endif %}
      icon_template: >-
        {% set state_status = state_attr('cover.ikea_blinds', 'current_position') | int %}
        {% if state_status > 90 and state_status > 70 %}
          mdi:blinds-open
        {% elif state_status < 70 and state_status > 40 %}
          mdi:gamepad-circle
        {% else %}
          mdi:blinds
        {% endif %}