- platform: "mqtt"
  unique_id: ikea_button_availability
  name: Кнопка жалюзи (Бар)_availability
  state_topic: "zigbee2mqtt/ikea_button/availability"
    
- platform: "mqtt"
  unique_id: ikea_button_click
  name: Кнопка жалюзи (Бар)_click
  state_topic: "zigbee2mqtt/ikea_button"
  availability_topic: "zigbee2mqtt/ikea_button/availability"
  icon: "mdi:toggle-switch"
  value_template: "{{ value_json.click }}"

- platform: "mqtt"
  unique_id: ikea_button_battery
  name: Кнопка жалюзи (Бар)_battery
  state_topic: "zigbee2mqtt/ikea_button"
  availability_topic: "zigbee2mqtt/ikea_button/availability"
  unit_of_measurement: "%"
  value_template: "{{ value_json.battery }}"
  device_class: "battery"

- platform: "mqtt"
  unique_id: ikea_button_action
  name: Кнопка жалюзи (Бар)_action
  state_topic: "zigbee2mqtt/ikea_button"
  availability_topic: "zigbee2mqtt/ikea_button/availability"
  value_template: "{{ value_json.action }}"
  icon: "mdi:gesture-double-tap"

# - platform: "mqtt"
#   unique_id: ikea_button_signal
#   name: Кнопка жалюзи (Бар)_signal
#   state_topic: "zigbee2mqtt/ikea_button"
#   availability_topic: "zigbee2mqtt/ikea_button/availability"
#   unit_of_measurement: "lqi"
#   value_template: "{{ value_json.linkquality }}"
#   icon: "mdi:signal"

# - platform: "mqtt"
#   unique_id: ikea_button_update_state
#   name: Кнопка жалюзи (Бар)_update_state
#   state_topic: "zigbee2mqtt/ikea_button"
#   availability_topic: "zigbee2mqtt/ikea_button/availability"
#   icon: "mdi:update"
#   value_template: "{{ value_json['update']['state'] }}"