- platform: "mqtt"
  unique_id: ikea_repeater_availability
  name: IKEA Рипитер (Общее)_availability
  state_topic: "zigbee2mqtt/ikea_repeater/availability"

# - platform: "mqtt"
#   unique_id: ikea_repeater_signal
#   name: IKEA Рипитер (Общее)_signal
#   state_topic: "zigbee2mqtt/ikea_repeater"
#   availability_topic: "zigbee2mqtt/ikea_repeater/availability"
#   unit_of_measurement: "lqi"
#   value_template: "{{ value_json.linkquality }}"
#   icon: "mdi:signal"

# - platform: "mqtt"
#   unique_id: ikea_repeater_update_state
#   name: IKEA Рипитер (Общее)_update_state
#   state_topic: "zigbee2mqtt/ikea_repeater"
#   availability_topic: "zigbee2mqtt/ikea_repeater/availability"
#   icon: "mdi:update"
#   value_template: "{{ value_json['update']['state'] }}"