- platform: "mqtt"
  unique_id: aqara_bar_left_window_availability
  name: Левое окно (Бар)_availability
  state_topic: "zigbee2mqtt/bar_left_window/availability"

# - platform: "mqtt"
#   unique_id: aqara_bar_left_window_temperature
#   name: Левое окно (Бар)_temperature
#   state_topic: "zigbee2mqtt/bar_left_window"
#   availability_topic: "zigbee2mqtt/bar_left_window/availability"
#   value_template: "{{ value_json.temperature }}"
#   unit_of_measurement: "°C"
#   device_class: "temperature"

# - platform: "mqtt"
#   unique_id: aqara_bar_left_window_voltage
#   name: Левое окно (Бар)_voltage
#   state_topic: "zigbee2mqtt/bar_left_window"
#   availability_topic: "zigbee2mqtt/bar_left_window/availability"
#   value_template: "{{ value_json.voltage }}"
#   unit_of_measurement: "mV"
#   device_class: "voltage"

# - platform: "mqtt"
#   unique_id: aqara_bar_left_window_signal
#   name: Левое окно (Бар)_signal
#   state_topic: "zigbee2mqtt/bar_left_window"
#   availability_topic: "zigbee2mqtt/bar_left_window/availability"
#   value_template: "{{ value_json.linkquality }}"
#   unit_of_measurement: "lqi"
#   icon: "mdi:signal"
  
- platform: "mqtt"
  unique_id: aqara_bar_left_window_battery
  name: Левое окно (Бар)_battery
  state_topic: "zigbee2mqtt/bar_left_window"
  availability_topic: "zigbee2mqtt/bar_left_window/availability"
  value_template: "{{ value_json.battery }}"
  unit_of_measurement: "%"
  device_class: "battery"
  
####################

- platform: "mqtt"
  unique_id: aqara_bar_big_window_availability
  name: Правое окно (Бар)_availability
  state_topic: "zigbee2mqtt/bar_big_window/availability"

# - platform: "mqtt"
#   unique_id: aqara_bar_big_window_temperature
#   name: Правое окно (Бар)_temperature
#   state_topic: "zigbee2mqtt/bar_big_window"
#   availability_topic: "zigbee2mqtt/bar_big_window/availability"
#   value_template: "{{ value_json.temperature }}"
#   unit_of_measurement: "°C"
#   device_class: "temperature"

# - platform: "mqtt"
#   unique_id: aqara_bar_big_window_voltage
#   name: Правое окно (Бар)_voltage
#   state_topic: "zigbee2mqtt/bar_big_window"
#   availability_topic: "zigbee2mqtt/bar_big_window/availability"
#   value_template: "{{ value_json.voltage }}"
#   unit_of_measurement: "mV"
#   device_class: "voltage"

# - platform: "mqtt"
#   unique_id: aqara_bar_big_window_signal
#   name: Правое окно (Бар)_signal
#   state_topic: "zigbee2mqtt/bar_big_window"
#   availability_topic: "zigbee2mqtt/bar_big_window/availability"
#   value_template: "{{ value_json.linkquality }}"
#   unit_of_measurement: "lqi"
#   icon: "mdi:signal"

- platform: "mqtt"
  unique_id: aqara_bar_big_window_battery
  name: Правое окно (Бар)_battery
  state_topic: "zigbee2mqtt/bar_big_window"
  availability_topic: "zigbee2mqtt/bar_big_window/availability"
  value_template: "{{ value_json.battery }}"
  unit_of_measurement: "%"
  device_class: "battery"
  
####################

- platform: "mqtt"
  unique_id: aqara_bar_small_window_availability
  name: Левое окно форточка (Бар)_availability
  state_topic: "zigbee2mqtt/bar_small_window/availability"

# - platform: "mqtt"
#   unique_id: aqara_bar_small_window_temperature
#   name: Левое окно форточка (Бар)_temperature
#   state_topic: "zigbee2mqtt/bar_small_window"
#   availability_topic: "zigbee2mqtt/bar_small_window/availability"
#   value_template: "{{ value_json.temperature }}"
#   unit_of_measurement: "°C"
#   device_class: "temperature"

# - platform: "mqtt"
#   unique_id: aqara_bar_small_window_voltage
#   name: Левое окно форточка (Бар)_voltage
#   state_topic: "zigbee2mqtt/bar_small_window"
#   availability_topic: "zigbee2mqtt/bar_small_window/availability"
#   value_template: "{{ value_json.voltage }}"
#   unit_of_measurement: "mV"
#   device_class: "voltage"

# - platform: "mqtt"
#   unique_id: aqara_bar_small_window_signal
#   name: Левое окно форточка (Бар)_signal
#   state_topic: "zigbee2mqtt/bar_small_window"
#   availability_topic: "zigbee2mqtt/bar_small_window/availability"
#   value_template: "{{ value_json.linkquality }}"
#   unit_of_measurement: "lqi"
#   icon: "mdi:signal"

- platform: "mqtt"
  unique_id: aqara_bar_small_window_battery
  name: Левое окно форточка (Бар)_battery
  state_topic: "zigbee2mqtt/bar_small_window"
  availability_topic: "zigbee2mqtt/bar_small_window/availability"
  value_template: "{{ value_json.battery }}"
  unit_of_measurement: "%"
  device_class: "battery"