- platform: "mqtt"
  unique_id: bathroom_radiator_switch_availability
  name: Розетка Полотенцесушитель (Ванная)_availability
  state_topic: "zigbee2mqtt/bathroom_radiator_switch/availability"
    
- platform: "mqtt"
  name: "Полотенцесушитель (Ванная)_power"
  unique_id: bath_radiator_switch_power
  state_topic: "zigbee2mqtt/bathroom_radiator_switch"
  availability_topic: "zigbee2mqtt/bathroom_radiator_switch/availability"
  value_template: "{{ value_json.power }}"
  unit_of_measurement: "W"
  device_class: "power"

- platform: "mqtt"
  name: "Полотенцесушитель (Ванная)_current"
  unique_id: bath_radiator_switch_current
  state_topic: "zigbee2mqtt/bathroom_radiator_switch"
  availability_topic: "zigbee2mqtt/bathroom_radiator_switch/availability"
  value_template: "{{ value_json.current }}"
  unit_of_measurement: "A"
  device_class: "current"

- platform: "mqtt"
  name: "Полотенцесушитель (Ванная)_voltage"
  unique_id: bath_radiator_switch_voltage
  state_topic: "zigbee2mqtt/bathroom_radiator_switch"
  availability_topic: "zigbee2mqtt/bathroom_radiator_switch/availability"
  value_template: "{{ value_json.voltage }}"
  unit_of_measurement: "V"
  device_class: "voltage"

- platform: "mqtt"
  name: "Полотенцесушитель (Ванная)_energy"
  unique_id: bath_radiator_switch_energy
  state_topic: "zigbee2mqtt/bathroom_radiator_switch"
  availability_topic: "zigbee2mqtt/bathroom_radiator_switch/availability"
  value_template: "{{ value_json.energy }}"
  unit_of_measurement: "kWh"
  device_class: "energy"

- platform: "mqtt"
  name: "Полотенцесушитель (Ванная)_power_outage_memory"
  unique_id: bath_radiator_switch_power_outage_memory
  state_topic: "zigbee2mqtt/bathroom_radiator_switch"
  availability_topic: "zigbee2mqtt/bathroom_radiator_switch/availability"
  value_template: "{{ value_json.power_outage_memory }}"

# - platform: "mqtt"
#   name: "Полотенцесушитель (Ванная)_signal"
#   unique_id: bath_radiator_switch_signal
#   state_topic: "zigbee2mqtt/bathroom_radiator_switch"
#   availability_topic: "zigbee2mqtt/bathroom_radiator_switch/availability"
#   value_template: "{{ value_json.linkquality }}"
#   unit_of_measurement: "lqi"
#   icon: "mdi:signal"
    
####################

- platform: "mqtt"
  unique_id: bathroom_washer_switch_availability
  name: Розетка Стиральная машина (Ванная)_availability
  state_topic: "zigbee2mqtt/bathroom_washer_switch/availability"
  
- platform: "mqtt"
  name: "Стиральная машина (Ванная)_power"
  unique_id: bathroom_washer_switch_power
  state_topic: "zigbee2mqtt/bathroom_washer_switch"
  availability_topic: "zigbee2mqtt/bathroom_washer_switch/availability"
  value_template: "{{ value_json.power }}"
  unit_of_measurement: "W"
  device_class: "power"

- platform: "mqtt"
  name: "Стиральная машина (Ванная)_current"
  unique_id: bathroom_washer_switch_current
  state_topic: "zigbee2mqtt/bathroom_washer_switch"
  availability_topic: "zigbee2mqtt/bathroom_washer_switch/availability"
  value_template: "{{ value_json.current }}"
  unit_of_measurement: "A"
  device_class: "current"

- platform: "mqtt"
  name: "Стиральная машина (Ванная)_voltage"
  unique_id: bathroom_washer_switch_voltage
  state_topic: "zigbee2mqtt/bathroom_washer_switch"
  availability_topic: "zigbee2mqtt/bathroom_washer_switch/availability"
  value_template: "{{ value_json.voltage }}"
  unit_of_measurement: "V"
  device_class: "voltage"

- platform: "mqtt"
  name: "Стиральная машина (Ванная)_energy"
  unique_id: bathroom_washer_switch_energy
  state_topic: "zigbee2mqtt/bathroom_washer_switch"
  availability_topic: "zigbee2mqtt/bathroom_washer_switch/availability"
  value_template: "{{ value_json.energy }}"
  unit_of_measurement: "kWh"
  device_class: "energy"

- platform: "mqtt"
  name: "Стиральная машина (Ванная)_power_outage_memory"
  unique_id: bathroom_washer_switch_power_outage_memory
  state_topic: "zigbee2mqtt/bathroom_washer_switch"
  availability_topic: "zigbee2mqtt/bathroom_washer_switch/availability"
  value_template: "{{ value_json.power_outage_memory }}"

# - platform: "mqtt"
#   name: "Стиральная машина (Ванная)_signal"
#   unique_id: bathroom_washer_switch_signal
#   state_topic: "zigbee2mqtt/bathroom_washer_switch"
#   availability_topic: "zigbee2mqtt/bathroom_washer_switch/availability"
#   value_template: "{{ value_json.linkquality }}"
#   unit_of_measurement: "lqi"
#   icon: "mdi:signal"