- platform: template
  sensors:
    xiaomi_cabinet_motion_availability_problem:
      friendly_name: "Датчик движения (Детская)_availability_problem"
      icon_template: > 
        {% if is_state('sensor.cabinet_motion_availability', 'offline') %}
          mdi:car-brake-alert 
        {% else %}
          mdi:car-brake-worn-linings
        {% endif %}
      value_template: >
        {% if is_state('sensor.cabinet_motion_availability', 'offline') %}
          ON
        {% else %}
          OFF
        {% endif %}
      device_class: "problem"
      
- platform: "mqtt"
  unique_id: cabinet_motion
  name: "Датчик движения (Детская)"
  state_topic: "zigbee2mqtt/cabinet_motion"
  availability_topic: "zigbee2mqtt/cabinet_motion/availability"
  value_template: "{{ value_json.occupancy }}"
  payload_on: true
  payload_off: false
  device_class: "motion"
