- platform: "mqtt"
  unique_id: sonoff_bar_temperature_availability
  name: Датчик температуры (Бар)_availability
  state_topic: "zigbee2mqtt/bar_temperature/availability"

- platform: "mqtt"
  unique_id: sonoff_bar_temperature_battery
  name: Датчик температуры (Бар)_battery
  state_topic: "zigbee2mqtt/bar_temperature"
  availability_topic: "zigbee2mqtt/bar_temperature/availability"
  value_template: "{{ value_json.battery }}"
  unit_of_measurement: "%"
  device_class: "battery"

- platform: "mqtt"
  unique_id: sonoff_bar_temperature
  name: Датчик температуры (Бар)_temperature
  state_topic: "zigbee2mqtt/bar_temperature"
  availability_topic: "zigbee2mqtt/bar_temperature/availability"
  value_template: "{{ value_json.temperature | round(0) }}"
  unit_of_measurement: "°C"
  device_class: "temperature"

- platform: "mqtt"
  unique_id: sonoff_bar_temperature_humidity
  name: Датчик температуры (Бар)_humidity
  state_topic: "zigbee2mqtt/bar_temperature"
  availability_topic: "zigbee2mqtt/bar_temperature/availability"
  value_template: "{{ value_json.humidity | round(0) }}"
  unit_of_measurement: "%"
  device_class: "humidity"

# - platform: "mqtt"
#   unique_id: sonoff_bar_temperature_signal
#   name: Датчик температуры (Бар)_signal
#   state_topic: "zigbee2mqtt/bar_temperature"
#   availability_topic: "zigbee2mqtt/bar_temperature/availability"
#   value_template: "{{ value_json.linkquality }}"
#   unit_of_measurement: "lqi"
#   icon: "mdi:signal"