####################

- platform: mqtt
  name: "Трекинговый свет (Зал)"
  unique_id: living_room_rail_lamps
  icon: mdi:track-light
  command_topic: "livingroom/cmnd/tuya_light/power3"
  state_topic: "livingroom/stat/tuya_light/RESULT"
  state_value_template: "{{ value_json.POWER3 }}"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: false
