- platform: "mqtt"
  unique_id: bar_availability
  name: Датчик движения (Бар)_availability
  state_topic: "zigbee2mqtt/bar/availability"

# - platform: "mqtt"
#   unique_id: bar_temperature
#   name: Датчик движения (Бар)_temperature
#   state_topic: "zigbee2mqtt/bar"
#   availability_topic: "zigbee2mqtt/bar/availability"
#   value_template: "{{ value_json.temperature }}"
#   unit_of_measurement: "°C"
#   device_class: "temperature"

# - platform: "mqtt"
#   unique_id: bar_voltage
#   name: Датчик движения (Бар)_voltage
#   state_topic: "zigbee2mqtt/bar"
#   availability_topic: "zigbee2mqtt/bar/availability"
#   value_template: "{{ value_json.voltage }}"
#   unit_of_measurement: "mV"
#   device_class: "voltage"

# - platform: "mqtt"
#   unique_id: bar_signal
#   name: Датчик движения (Бар)_signal
#   state_topic: "zigbee2mqtt/bar"
#   availability_topic: "zigbee2mqtt/bar/availability"
#   value_template: "{{ value_json.linkquality }}"
#   unit_of_measurement: "lqi"
#   icon: "mdi:signal"
  
- platform: "mqtt"
  unique_id: bar_battery
  name: Датчик движения (Бар)_battery
  state_topic: "zigbee2mqtt/bar"
  availability_topic: "zigbee2mqtt/bar/availability"
  value_template: "{{ value_json.battery }}"
  unit_of_measurement: "%"
  device_class: "battery"
  
- platform: "mqtt"
  unique_id: bar_Illuminance_lux
  name: Датчик движения (Бар)_Illuminance_lux
  state_topic: "zigbee2mqtt/bar"
  availability_topic: "zigbee2mqtt/bar/availability"
  value_template: "{{ value_json.illuminance_lux }}"
  unit_of_measurement: "1x"

- platform: "mqtt"
  unique_id: bar_Illuminance
  name: Датчик движения (Бар)_Illuminance
  state_topic: "zigbee2mqtt/bar"
  availability_topic: "zigbee2mqtt/bar/availability"
  value_template: "{{ value_json.illuminance }}"
  unit_of_measurement: "1x"