- platform: mqtt
  name: "Основной свет (Бар)"
  unique_id: bar_main_lamp
  icon: mdi:dome-light
  command_topic: "bar/cmnd/tuya_light/power1"
  state_topic: "bar/stat/tuya_light/RESULT"
  value_template: "{{ value_json.POWER1 }}"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: false

- platform: mqtt
  name: "Свет над столом (Бар)"
  unique_id: bar_underlight
  icon: mdi:spotlight-beam
  command_topic: "bar/cmnd/tuya_light/power2"
  state_topic: "bar/stat/tuya_light/RESULT"
  value_template: "{{ value_json.POWER2 }}"
  payload_available: "Online"
  payload_not_available: "Offline"
  state_on: "ON"
  state_off: "OFF"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: false

