- platform: template
  sensors:
    levoe_okno_detskaia_availability_problem:
      friendly_name: "Левое окно (Детская)_availability_problem"
      icon_template: > 
        {% if is_state('sensor.levoe_okno_detskaia_availability', 'offline') %}
          mdi:car-brake-alert 
        {% else %}
          mdi:car-brake-worn-linings
        {% endif %}
      value_template: >
        {% if is_state('sensor.levoe_okno_detskaia_availability', 'offline') %}
          ON
        {% else %}
          OFF
        {% endif %}
      device_class: "problem"

####################

- platform: template
  sensors:
    pravoe_okno_detskaia_availability_problem:
      friendly_name: "Правое окно (Детская)_availability_problem"
      icon_template: > 
        {% if is_state('sensor.pravoe_okno_detskaia_availability', 'offline') %}
          mdi:car-brake-alert 
        {% else %}
          mdi:car-brake-worn-linings
        {% endif %}
      value_template: >
        {% if is_state('sensor.pravoe_okno_detskaia_availability', 'offline') %}
          ON
        {% else %}
          OFF
        {% endif %}
      device_class: "problem"