- platform: template
  sensors:
    aqara_cabinet_floor_temperature_availability_problem:
      friendly_name: "Датчик температуры на полу (Детская)_availability_problem"
      icon_template: > 
        {% if is_state('sensor.aqara_cabinet_floor_temperature_availability', 'offline') %}
          mdi:car-brake-alert 
        {% else %}
          mdi:car-brake-worn-linings
        {% endif %}
      value_template: >
        {% if is_state('sensor.aqara_cabinet_floor_temperature_availability', 'offline') %}
          ON
        {% else %}
          OFF
        {% endif %}
      device_class: "problem"
    
####################

- platform: template
  sensors:
    aqara_cabinet_temperature_availability_problem:
      friendly_name: "Датчик температуры (Детская)_availability_problem"
      icon_template: > 
        {% if is_state('sensor.aqara_cabinet_temperature_availability', 'offline') %}
          mdi:car-brake-alert 
        {% else %}
          mdi:car-brake-worn-linings
        {% endif %}
      value_template: >
        {% if is_state('sensor.aqara_cabinet_temperature_availability', 'offline') %}
          ON
        {% else %}
          OFF
        {% endif %}
      device_class: "problem"