- alias: "[Трекинговый свет (Спальня)] - Переключать состояние трекинговых ламп в спальне через MQTT"
  id: toggle_bedroom_rail_lamps
  trigger:
    - platform: mqtt
      topic: "zigbee2mqtt/bedroom_switch/action"
      # Optional
      payload: "button_2_single"
      encoding: "utf-8"
  action:
     - service: light.toggle
       entity_id: light.bedroom_rail_lamps
     - delay: 0.5
     - service: mqtt.publish
       data:
         topic: "bedroom/stat/moes/RESULT"
         retain: false
         payload: "{\"POWER\":\"{{ states('light.bedroom_rail_lamps') }}\"}"
       
- alias: "[Трекинговый свет (Спальня)] - Включать трекинговые лампы в спальне через MQTT"
  trigger:
    - platform: mqtt
      topic: "bedroom/cmnd/moes/power"
      # Optional
      payload: "ON"
      encoding: "utf-8"
  action:
     - service: switch.turn_on
       entity_id: switch.bedroom_rail_lamps
     - delay: 0.5
     - service: mqtt.publish
       data:
         topic: "bedroom/stat/moes/RESULT"
         retain: false
         payload: "{\"POWER\":\"{{ states('light.bedroom_rail_lamps') }}\"}"
         
- alias: "[Трекинговый свет (Спальня)] - Выключать трекинговые лампы в спальне через MQTT"
  trigger:
    - platform: mqtt
      topic: "bedroom/cmnd/moes/power"
      # Optional
      payload: "OFF"
      encoding: "utf-8"
  action:
     - service: light.turn_off
       entity_id: light.bedroom_rail_lamps
     - delay: 2
     - service: mqtt.publish
       data:
         topic: "bedroom/stat/moes/RESULT"
         retain: false
         payload: "{\"POWER\":\"{{ states('light.bedroom_rail_lamps') }}\"}"
         
