- alias: "[Трекинговый свет (Спальня)] - Переключать состояние трекинговых ламп в спальне через MQTT"
  id: toggle_bedroom_rail_lamps
  trigger:
    - platform: mqtt
      topic: "zigbee2mqtt/bedroom_switch/action"
      # Optional
      payload: "button_2_single"
      encoding: "utf-8"
  action:
     - service: light.toggle
       entity_id: light.trekingovyi_svet_spalnia
     - delay: 0.5
     - service: mqtt.publish
       data:
         topic: "bedroom/stat/moes/RESULT"
         retain: false
         payload: "{\"POWER\":\"{{ states('light.trekingovyi_svet_spalnia') }}\"}"
         
