- alias: "[Battery] - Low Battery Alert"
  id: low_battery_alert
  trigger:
    - platform: event
      event_type: state_changed
  condition:
    - condition: template
      value_template: >-
        {{ trigger.event.data.entity_id in (expand('group.battery_devices') | map(attribute='entity_id')) }}
    - condition: template
      value_template: >-
        {{ not trigger.event.data.new_state.state in ['unknown', 'unavailable'] }}
    - condition: template
      value_template: >-
        {{ (trigger.event.data.new_state.state | int) < 20 }}
  action:
    - service: telegram_bot.send_message
      data:
        title: "<b>Статус батареек критический</b>"
        message: >
          {{ trigger.event.data.new_state.attributes.friendly_name }}: {{ trigger.event.data.new_state.state }}%!
        target:
          - !secret telegram_id_1
          - !secret telegram_id_2
        disable_notification: false