- platform: template
  sensors:
    livingroom_xiaomi_purifier_humidity:
      #friendly_name: "Влажность"
      unique_id: livingroom_xiaomi_purifier_humidity
#      entity_id: fan.xiaomi_purifier_3
      unit_of_measurement: "%"
      value_template: >
        {{ states.sensor.zhimi_airpurifier_ma4_humidity.state | round(0) }}
    
    livingroom_xiaomi_purifier_temperature:
      #friendly_name: "Температура"
      unique_id: livingroom_xiaomi_purifier_temperature
      unit_of_measurement: "°C"
      value_template: >
        {{ states.sensor.zhimi_airpurifier_ma4_temperature.state | round(0) }}
    