- platform: "mqtt"
  unique_id: aqara_cabinet_left_window_availability
  name: Левое окно (Детская)_availability
  state_topic: "zigbee2mqtt/cabinet_left_window/availability"

# - platform: "mqtt"
#   unique_id: aqara_cabinet_left_window_temperature
#   name: Левое окно (Детская)_temperature
#   state_topic: "zigbee2mqtt/cabinet_left_window"
#   availability_topic: "zigbee2mqtt/cabinet_left_window/availability"
#   value_template: "{{ value_json.temperature }}"
#   unit_of_measurement: "°C"
#   device_class: "temperature"

# - platform: "mqtt"
#   unique_id: aqara_cabinet_left_window_voltage
#   name: Левое окно (Детская)_voltage
#   state_topic: "zigbee2mqtt/cabinet_left_window"
#   availability_topic: "zigbee2mqtt/cabinet_left_window/availability"
#   value_template: "{{ value_json.voltage }}"
#   unit_of_measurement: "mV"
#   device_class: "voltage"

# - platform: "mqtt"
#   unique_id: aqara_cabinet_left_window_signal
#   name: Левое окно (Детская)_signal
#   state_topic: "zigbee2mqtt/cabinet_left_window"
#   availability_topic: "zigbee2mqtt/cabinet_left_window/availability"
#   value_template: "{{ value_json.linkquality }}"
#   unit_of_measurement: "lqi"
#   icon: "mdi:signal"
  
- platform: "mqtt"
  unique_id: aqara_cabinet_left_window_battery
  name: Левое окно (Детская)_battery
  state_topic: "zigbee2mqtt/cabinet_left_window"
  availability_topic: "zigbee2mqtt/cabinet_left_window/availability"
  value_template: "{{ value_json.battery }}"
  unit_of_measurement: "%"
  device_class: "battery"
  
####################

- platform: "mqtt"
  unique_id: aqara_cabinet_right_window_availability
  name: Правое окно (Детская)_availability
  state_topic: "zigbee2mqtt/cabinet_right_window/availability" 
  
# - platform: "mqtt"
#   unique_id: aqara_cabinet_right_window_temperature
#   name: Правое окно (Детская)_temperature
#   state_topic: "zigbee2mqtt/cabinet_right_window"
#   availability_topic: "zigbee2mqtt/cabinet_right_window/availability"
#   value_template: "{{ value_json.temperature }}"
#   unit_of_measurement: "°C"
#   device_class: "temperature"

# - platform: "mqtt"
#   unique_id: aqara_cabinet_right_window_voltage
#   name: Правое окно (Детская)_voltage
#   state_topic: "zigbee2mqtt/cabinet_right_window"
#   availability_topic: "zigbee2mqtt/cabinet_right_window/availability"
#   value_template: "{{ value_json.voltage }}"
#   unit_of_measurement: "mV"
#   device_class: "voltage"

# - platform: "mqtt"
#   unique_id: aqara_cabinet_right_window_signal
#   name: Правое окно (Детская)_signal
#   state_topic: "zigbee2mqtt/cabinet_right_window"
#   availability_topic: "zigbee2mqtt/cabinet_right_window/availability"
#   value_template: "{{ value_json.linkquality }}"
#   unit_of_measurement: "lqi"
#   icon: "mdi:signal"
  
- platform: "mqtt"
  unique_id: aqara_cabinet_right_window_battery
  name: Правое окно (Детская)_battery
  state_topic: "zigbee2mqtt/cabinet_right_window"
  availability_topic: "zigbee2mqtt/cabinet_right_window/availability"
  value_template: "{{ value_json.battery }}"
  unit_of_measurement: "%"
  device_class: "battery"