- platform: "mqtt"
  unique_id: aqara_cabinet_floor_temperature_availability
  name: Датчик температуры на полу (Детская)_availability
  state_topic: "zigbee2mqtt/cabinet_floor_temperature/availability"
  
- platform: "mqtt"
  unique_id: aqara_cabinet_floor_temperature_battery
  name: Датчик температуры на полу (Детская)_battery
  state_topic: "zigbee2mqtt/cabinet_floor_temperature"
  availability_topic: "zigbee2mqtt/cabinet_floor_temperature/availability"
  value_template: "{{ value_json.battery }}"
  unit_of_measurement: "%"
  device_class: "battery"

- platform: "mqtt"
  unique_id: aqara_cabinet_floor_temperature
  name: Датчик температуры на полу (Детская)_temperature
  state_topic: "zigbee2mqtt/cabinet_floor_temperature"
  availability_topic: "zigbee2mqtt/cabinet_floor_temperature/availability"
  value_template: "{{ value_json.temperature | round(0) }}"
  unit_of_measurement: "°C"
  device_class: "temperature"

- platform: "mqtt"
  unique_id: aqara_cabinet_floor_temperature_humidity
  name: Датчик температуры на полу (Детская)_humidity
  state_topic: "zigbee2mqtt/cabinet_floor_temperature"
  availability_topic: "zigbee2mqtt/cabinet_floor_temperature/availability"
  value_template: "{{ value_json.humidity | round(0) }}"
  unit_of_measurement: "%"
  device_class: "humidity"

# - platform: "mqtt"
#   unique_id: aqara_cabinet_floor_temperature_pressure
#   name: Датчик температуры на полу (Детская)_pressure
#   state_topic: "zigbee2mqtt/cabinet_floor_temperature"
#   availability_topic: "zigbee2mqtt/cabinet_floor_temperature/availability"
#   value_template: "{{ value_json.pressure }}"
#   unit_of_measurement: "hPa"
#   device_class: "pressure"

# - platform: "mqtt"
#   unique_id: aqara_cabinet_floor_temperature_voltage
#   name: Датчик температуры на полу (Детская)_voltage
#   state_topic: "zigbee2mqtt/cabinet_floor_temperature"
#   availability_topic: "zigbee2mqtt/cabinet_floor_temperature/availability"
#   value_template: "{{ value_json.voltage }}"
#   unit_of_measurement: "mV"
#   device_class: "voltage"

# - platform: "mqtt"
#   unique_id: aqara_cabinet_floor_temperature_signal
#   name: Датчик температуры на полу (Детская)_signal
#   state_topic: "zigbee2mqtt/cabinet_floor_temperature"
#   availability_topic: "zigbee2mqtt/cabinet_floor_temperature/availability"
#   value_template: "{{ value_json.linkquality }}"
#   unit_of_measurement: "lqi"
#   icon: "mdi:signal"
    
####################

- platform: "mqtt"
  unique_id: aqara_cabinet_temperature_availability
  name: Датчик температуры (Детская)_availability
  state_topic: "zigbee2mqtt/cabinet_temperature/availability"

- platform: "mqtt"
  unique_id: aqara_cabinet_temperature_battery
  name: Датчик температуры (Детская)_battery
  state_topic: "zigbee2mqtt/cabinet_temperature"
  availability_topic: "zigbee2mqtt/cabinet_temperature/availability"
  value_template: "{{ value_json.battery }}"
  unit_of_measurement: "%"
  device_class: "battery"

- platform: "mqtt"
  unique_id: aqara_cabinet_temperature
  name: Датчик температуры (Детская)_temperature
  state_topic: "zigbee2mqtt/cabinet_temperature"
  availability_topic: "zigbee2mqtt/cabinet_temperature/availability"
  value_template: "{{ value_json.temperature | round(0) }}"
  unit_of_measurement: "°C"
  device_class: "temperature"

- platform: "mqtt"
  unique_id: aqara_cabinet_temperature_humidity
  name: Датчик температуры (Детская)_humidity
  state_topic: "zigbee2mqtt/cabinet_temperature"
  availability_topic: "zigbee2mqtt/cabinet_temperature/availability"
  value_template: "{{ value_json.humidity | round(0) }}"
  unit_of_measurement: "%"
  device_class: "humidity"

# - platform: "mqtt"
#   unique_id: aqara_cabinet_temperature_pressure
#   name: Датчик температуры (Детская)_pressure
#   state_topic: "zigbee2mqtt/cabinet_temperature"
#   availability_topic: "zigbee2mqtt/cabinet_temperature/availability"
#   value_template: "{{ value_json.pressure }}"
#   unit_of_measurement: "hPa"
#   device_class: "pressure"

# - platform: "mqtt"
#   unique_id: aqara_cabinet_temperature_voltage
#   name: Датчик температуры (Детская)_voltage
#   state_topic: "zigbee2mqtt/cabinet_temperature"
#   availability_topic: "zigbee2mqtt/cabinet_temperature/availability"
#   value_template: "{{ value_json.voltage }}"
#   unit_of_measurement: "mV"
#   device_class: "voltage"

# - platform: "mqtt"
#   unique_id: aqara_cabinet_temperature_signal
#   name: Датчик температуры (Детская)_signal
#   state_topic: "zigbee2mqtt/cabinet_temperature"
#   availability_topic: "zigbee2mqtt/cabinet_temperature/availability"
#   value_template: "{{ value_json.linkquality }}"
#   unit_of_measurement: "lqi"
#   icon: "mdi:signal"