- platform: template
  sensors:
    datchik_dvizheniia_bar_availability:
      friendly_name: "Датчик движения (Бар)_availability_problem"
      icon_template: > 
        {% if is_state('sensor.datchik_dvizheniia_bar_availability', 'offline') %}
          mdi:car-brake-alert 
        {% else %}
          mdi:car-brake-worn-linings
        {% endif %}
      value_template: >
        {% if is_state('sensor.datchik_dvizheniia_bar_availability', 'offline') %}
          ON
        {% else %}
          OFF
        {% endif %}
      device_class: "problem"