- alias: "[Дополнительный свет (Зал)] - Переключать состояние Philips в зале через MQTT"
  id: toggle_livingroom_philips
  trigger:
    - platform: mqtt
      topic: "livingroom/cmnd/xiaomi_philips_light/power"
      # Optional
      payload: "TOGGLE"
      encoding: "utf-8"
  action:
    - service: homeassistant.toggle
      target:
        entity_id: light.zal_tsvetnye_malenkie
    - delay: 0.5
    - service: mqtt.publish
      data:
        topic: "livingroom/stat/xiaomi_philips_light/RESULT"
        retain: false
        payload: "{\"POWER\":\"{{ states('light.zal_tsvetnye_malenkie') }}\"}"
                
#################

- alias: "[Основной свет (Зал)] - Переключать состояние Philips в зале через MQTT"
  id: toggle_livingroom_philips_main
  trigger:
    - platform: mqtt
      topic: "livingroom/cmnd/xiaomi_philips_light_main/power"
      # Optional
      payload: "TOGGLE"
      encoding: "utf-8"
  action:
    - service: homeassistant.toggle
      target:
        entity_id: light.zal_tsvetnye
    - delay: 0.5
    - service: mqtt.publish
      data:
        topic: "livingroom/stat/xiaomi_philips_light_main/RESULT"
        retain: false
        payload: "{\"POWER\":\"{{ states('light.zal_tsvetnye') }}\"}"
        
