- platform: "mqtt"
  unique_id: aqara_bath_door_availability
  name: Дверь (Ванная)_availability
  state_topic: "zigbee2mqtt/bath_door/availability"
  
# - platform: "mqtt"
#   unique_id: aqara_bath_door_temperature
#   name: Дверь (Ванная)_temperature
#   state_topic: "zigbee2mqtt/bath_door"
#   availability_topic: "zigbee2mqtt/bath_door/availability"
#   value_template: "{{ value_json.temperature }}"
#   unit_of_measurement: "°C"
#   device_class: "temperature"

# - platform: "mqtt"
#   unique_id: aqara_bath_door_voltage
#   name: Дверь (Ванная)_voltage
#   state_topic: "zigbee2mqtt/bath_door"
#   availability_topic: "zigbee2mqtt/bath_door/availability"
#   value_template: "{{ value_json.voltage }}"
#   unit_of_measurement: "mV"
#   device_class: "voltage"

# - platform: "mqtt"
#   unique_id: aqara_bath_door_signal
#   name: Дверь (Ванная)_signal
#   state_topic: "zigbee2mqtt/bath_door"
#   availability_topic: "zigbee2mqtt/bath_door/availability"
#   value_template: "{{ value_json.linkquality }}"
#   unit_of_measurement: "lqi"
#   icon: "mdi:signal"
  
- platform: "mqtt"
  unique_id: aqara_bath_door_battery
  name: Дверь (Ванная)_battery
  state_topic: "zigbee2mqtt/bath_door"
  availability_topic: "zigbee2mqtt/bath_door/availability"
  value_template: "{{ value_json.battery }}"
  unit_of_measurement: "%"
  device_class: "battery"