- platform: "mqtt"
  unique_id: aqara_livingroom_leak_availability
  name: Датчик утечки воды (Зал)_availability
  state_topic: "zigbee2mqtt/livingroom_leak/availability"

- platform: "mqtt"
  unique_id: aqara_livingroom_leak_battery
  name: Датчик утечки воды (Зал)_battery
  state_topic: "zigbee2mqtt/livingroom_leak"
  availability_topic: "zigbee2mqtt/livingroom_leak/availability"
  value_template: "{{ value_json.battery }}"
  unit_of_measurement: "%"
  device_class: "battery"

# - platform: "mqtt"
#   unique_id: aqara_livingroom_leak_voltage
#   name: Датчик утечки воды (Зал)_voltage
#   state_topic: "zigbee2mqtt/livingroom_leak"
#   availability_topic: "zigbee2mqtt/livingroom_leak/availability"
#   value_template: "{{ value_json.voltage }}"
#   unit_of_measurement: "mV"
#   device_class: "voltage"

# - platform: "mqtt"
#   unique_id: aqara_livingroom_leak_signal
#   name: Датчик утечки воды (Зал)_signal
#   state_topic: "zigbee2mqtt/livingroom_leak"
#   availability_topic: "zigbee2mqtt/livingroom_leak/availability"
#   value_template: "{{ value_json.linkquality }}"
#   unit_of_measurement: "lqi"
#   icon: "mdi:signal"