- alias: cicle_light_color_sync
  initial_state: true
  trigger:
  - platform: state
    entity_id: input_select.cicle_light_color
  action:
  - service: light.turn_on
    entity_id: light.yeelight_stripa_0x19db0b1e
    data_template:
      color_name: >
        {{trigger.to_state.state}}
      transition: 2

- alias: cicle_light_color_change
  initial_state: false
  trigger:
  - platform: time_pattern
    seconds: '/5'
  action:
  - service: input_select.select_next
    target:
      entity_id: input_select.cicle_light_color