- platform: template
  sensors:
    zhaliuzi_bar_state:
      friendly_name: 'Жалюзи (Бар)_status'
      value_template: >-
        {% set state_status = state_attr('cover.zhaliuzi_bar', 'current_position') | int %}
        {% if state_status > 90 and state_status > 70 %}
          Открыты
        {% elif state_status < 70 and state_status > 40 %}
          Полуоткрыты
        {% else %}
          Закрыты
        {% endif %}
      icon_template: >-
        {% set state_status = state_attr('cover.zhaliuzi_bar', 'current_position') | int %}
        {% if state_status > 90 and state_status > 70 %}
          mdi:blinds-open
        {% elif state_status < 70 and state_status > 40 %}
          mdi:gamepad-circle
        {% else %}
          mdi:blinds
        {% endif %}