- platform: template
  sensors:
    datchik_utechki_vody_pod_vannoi_vannaia_availability_problem:
      friendly_name: "Датчик утечки воды под ванной (Ванная)_availability_problem"
      icon_template: > 
        {% if is_state('sensor.datchik_utechki_vody_pod_vannoi_vannaia_availability', 'offline') %}
          mdi:car-brake-alert 
        {% else %}
          mdi:car-brake-worn-linings
        {% endif %}
      value_template: >
        {% if is_state('sensor.datchik_utechki_vody_pod_vannoi_vannaia_availability', 'offline') %}
          ON
        {% else %}
          OFF
        {% endif %}
      device_class: "problem"
  
####################

- platform: template
  sensors:
    datchik_utechki_vody_pod_rakovinoi_vannaia_availability_problem:
      friendly_name: "Датчик утечки воды под раковиной (Ванная)_availability_problem"
      icon_template: > 
        {% if is_state('sensor.datchik_utechki_vody_pod_rakovinoi_vannaia_availability', 'offline') %}
          mdi:car-brake-alert 
        {% else %}
          mdi:car-brake-worn-linings
        {% endif %}
      value_template: >
        {% if is_state('sensor.datchik_utechki_vody_pod_rakovinoi_vannaia_availability', 'offline') %}
          ON
        {% else %}
          OFF
        {% endif %}
      device_class: "problem"