- platform: mqtt
  name: "Теплый пол (Детская)_sensor"
  unique_id: cabinet_thermostat_sensor
  icon: mdi:dome-light
  command_topic: "zigbee2mqtt/cabinet_thermostat/set/sensor"
  state_topic: "zigbee2mqtt/cabinet_thermostat"
  value_template: "{{ value_json.sensor }}"
  state_on: "OU"
  state_off: "IN"
  qos: 1
  payload_on: "OU"
  payload_off: "IN"
  retain: false
  
- platform: mqtt
  name: "Теплый пол (Детская)_Авто"
  unique_id: cabinet_thermostat_preset_program
  command_topic: "zigbee2mqtt/cabinet_thermostat/set/preset"
  state_topic: "zigbee2mqtt/cabinet_thermostat"
  value_template: "{{ value_json.preset }}"
  state_on: "program"
  state_off: "hold"
  payload_on: "program"
  payload_off: "hold"
  retain: false
  
- platform: mqtt
  name: "Теплый пол (Детская)_Вручную"
  unique_id: cabinet_thermostat_preset_hold
  command_topic: "zigbee2mqtt/cabinet_thermostat/set/preset"
  state_topic: "zigbee2mqtt/cabinet_thermostat"
  value_template: "{{ value_json.preset }}"
  state_on: "hold"
  state_off: "program"
  payload_on: "hold"
  payload_off: "program"
  qos: 1
  retain: false