- platform: template
  sensors:
    count_zwaves:
      friendly_name: 'Zwave Devices'
      value_template: >
        {%- set domains = ['zwave'] -%}
        {%- for domain in domains -%}
          {%- for item in states[domain] -%}
            {% if loop.first %}
              {{loop.length}}
            {% endif %}
          {%- endfor -%}
        {%- endfor -%}
