- platform: template
  sensors:
    count_input_numbers:
      friendly_name: 'Input Numbers'
      value_template: >
        {%- set domains = ['input_number'] -%}
        {%- for domain in domains -%}
          {%- for item in states[domain] -%}
            {% if loop.first %}
              {{loop.length}}
            {% endif %}
          {%- endfor -%}
        {%- endfor -%}
