- platform: template
  sensors:
    count_timers:
      friendly_name: 'Timers'
      value_template: >
        {%- set domains = ['timer'] -%}
        {%- for domain in domains -%}
          {%- for item in states[domain] -%}
            {% if loop.first %}
              {{loop.length}}
            {% endif %}
          {%- endfor -%}
        {%- endfor -%}
