- platform: "mqtt"
  unique_id: bedroom_ac_switch_availability
  name: Розетка Кондиционер (Спальня)_availability
  state_topic: "zigbee2mqtt/bedroom_ac_switch/availability"

- platform: "mqtt"
  name: "Кондиционер (Спальня)_power"
  unique_id: bedroom_ac_switch_power
  state_topic: "zigbee2mqtt/bedroom_ac_switch"
  availability_topic: "zigbee2mqtt/bedroom_ac_switch/availability"
  value_template: "{{ value_json.power }}"
  unit_of_measurement: "W"
  device_class: "power"

- platform: "mqtt"
  name: "Кондиционер (Спальня)_current"
  unique_id: bedroom_ac_switch_current
  state_topic: "zigbee2mqtt/bedroom_ac_switch"
  availability_topic: "zigbee2mqtt/bedroom_ac_switch/availability"
  value_template: "{{ value_json.current }}"
  unit_of_measurement: "A"
  device_class: "current"

- platform: "mqtt"
  name: "Кондиционер (Спальня)_voltage"
  unique_id: bedroom_ac_switch_voltage
  state_topic: "zigbee2mqtt/bedroom_ac_switch"
  availability_topic: "zigbee2mqtt/bedroom_ac_switch/availability"
  value_template: "{{ value_json.voltage }}"
  unit_of_measurement: "V"
  device_class: "voltage"

- platform: "mqtt"
  name: "Кондиционер (Спальня)_energy"
  unique_id: bedroom_ac_switch_energy
  state_topic: "zigbee2mqtt/bedroom_ac_switch"
  availability_topic: "zigbee2mqtt/bedroom_ac_switch/availability"
  value_template: "{{ value_json.energy }}"
  unit_of_measurement: "kWh"
  device_class: "energy"

- platform: "mqtt"
  name: "Кондиционер (Спальня)_power_outage_memory"
  unique_id: bedroom_ac_switch_power_outage_memory
  state_topic: "zigbee2mqtt/bedroom_ac_switch"
  availability_topic: "zigbee2mqtt/bedroom_ac_switch/availability"
  value_template: "{{ value_json.power_outage_memory }}"

# - platform: "mqtt"
#   name: "Кондиционер (Спальня)_signal"
#   unique_id: bedroom_ac_switch_signal
#   state_topic: "zigbee2mqtt/bedroom_ac_switch"
#   availability_topic: "zigbee2mqtt/bedroom_ac_switch/availability"
#   value_template: "{{ value_json.linkquality }}"
#   unit_of_measurement: "lqi"
#   icon: "mdi:signal"