- platform: mqtt
  name: "Розетка телевизор (Зал)"
  unique_id: living_room_tv
  icon: mdi:television
  command_topic: "livingroom/cmnd/sonoff_switch_tv/power"
  state_topic: "livingroom/stat/sonoff_switch_tv/RESULT"
  value_template: "{{ value_json.POWER }}"
  payload_available: "Online"
  payload_not_available: "Offline"
  state_on: "ON"
  state_off: "OFF" 
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: false

####################

- platform: mqtt
  name: "Розетка XBOX (Зал)"
  unique_id: living_room_xbox
  icon: mdi:microsoft-xbox
  command_topic: "livingroom/cmnd/sonoff_switch_xbox/power"
  state_topic: "livingroom/stat/sonoff_switch_xbox/RESULT"
  value_template: "{{ value_json.POWER }}"
  payload_available: "Online"
  payload_not_available: "Offline"
  state_on: "ON"
  state_off: "OFF"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: false