- platform: template
  sensors:
    knopka_podsvetki_vannaia_availability_problem:
      friendly_name: " Кнопка подсветки (Ванная)_availability_problem"
      icon_template: > 
        {% if is_state('sensor.knopka_podsvetki_vannaia_availability', 'offline') %}
          mdi:car-brake-alert 
        {% else %}
          mdi:car-brake-worn-linings
        {% endif %}
      value_template: >
        {% if is_state('sensor.knopka_podsvetki_vannaia_availability', 'offline') %}
          ON
        {% else %}
          OFF
        {% endif %}
      device_class: "problem"