- platform: mqtt
  name: "Основной свет (Бар)"
  unique_id: bar_mainlamp
  icon: mdi:dome-light
  command_topic: "bar/cmnd/tuya_light/power1"
  state_topic: "bar/stat/tuya_light/RESULT"
  state_value_template: "{{ value_json.POWER1 }}"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: false
