- platform: "mqtt"
  name: "Розетка Кондиционер (Спальня)"
  unique_id: bedroom_ac_switch
  state_topic: "zigbee2mqtt/bedroom_ac_switch"
  availability_topic: "zigbee2mqtt/bedroom_ac_switch/availability"
  payload_off: "OFF"
  payload_on: "ON"
  value_template: "{{ value_json.state }}"
  command_topic: "zigbee2mqtt/bedroom_ac_switch/set"