- platform: mqtt
  name: "Розетка телевизор (Спальня)"
  unique_id: bedroom_tv
  icon: mdi:television
  command_topic: "bedroom/cmnd/sonoff_switch_tv/power"
  state_topic: "bedroom/stat/sonoff_switch_tv/RESULT"
  value_template: "{{ value_json.POWER }}"
  payload_available: "Online"
  payload_not_available: "Offline"
  state_on: "ON"
  state_off: "OFF"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: false