- platform: template
  sensors:
    aqara_kitchen_leak_availability_problem:
      friendly_name: "Датчик утечки воды под посудомойкой (Кухня)_availability_problem"
      icon_template: > 
        {% if is_state('sensor.aqara_kitchen_leak_availability', 'offline') %}
          mdi:car-brake-alert 
        {% else %}
          mdi:car-brake-worn-linings
        {% endif %}
      value_template: >
        {% if is_state('sensor.aqara_kitchen_leak_availability', 'offline') %}
          ON
        {% else %}
          OFF
        {% endif %}
      device_class: "problem"

- platform: "mqtt"
  unique_id: aqara_kitchen_leak_water_leak
  name: "! Датчик утечки воды под посудомойкой (Кухня)"
  state_topic: "zigbee2mqtt/kitchen_leak"
  availability_topic: "zigbee2mqtt/kitchen_leak/availability"
  value_template: "{{ value_json.water_leak }}"
  payload_on: true
  payload_off: false
  device_class: "moisture"

- platform: "mqtt"
  unique_id: aqara_kitchen_leak_battery_low
  name: Датчик утечки воды под посудомойкой (Кухня)_батарейка_низкая
  state_topic: "zigbee2mqtt/kitchen_leak"
  availability_topic: "zigbee2mqtt/kitchen_leak/availability"
  value_template: "{{ value_json.battery_low }}"
  payload_on: true
  payload_off: false
  device_class: "battery"

- platform: "mqtt"
  unique_id: aqara_kitchen_leak_tamper
  name: Датчик утечки воды под посудомойкой (Кухня)_тампер
  state_topic: "zigbee2mqtt/kitchen_leak"
  availability_topic: "zigbee2mqtt/kitchen_leak/availability"
  value_template: "{{ value_json.tamper }}"
  payload_on: true
  payload_off: false