- platform: template
  sensors:
    datchik_utechki_vody_pod_posudomoikoi_kukhnia_availability_problem:
      friendly_name: "Датчик утечки воды под посудомойкой (Кухня)_availability_problem"
      icon_template: > 
        {% if is_state('sensor.datchik_utechki_vody_pod_posudomoikoi_kukhnia_availability', 'offline') %}
          mdi:car-brake-alert 
        {% else %}
          mdi:car-brake-worn-linings
        {% endif %}
      value_template: >
        {% if is_state('sensor.datchik_utechki_vody_pod_posudomoikoi_kukhnia_availability', 'offline') %}
          ON
        {% else %}
          OFF
        {% endif %}
      device_class: "problem"