- alias: '[ Alarm ] - Detected'
  trigger:
  - platform: state
    entity_id: binary_sensor.datchik_dvizheniia_detskaia
    to: 'on'
  - platform: state
    entity_id: binary_sensor.datchik_dvizheniia_bar
    to: 'on'
  - platform: state
    entity_id: binary_sensor.datchik_dvizheniia_zal
    to: 'on'
  - platform: state
    entity_id: binary_sensor.datchik_dvizheniia_kukhnia
    to: 'on'
  - platform: state
    entity_id: binary_sensor.datchik_dvizheniia_spalnia
    to: 'on'
  - platform: state
    entity_id: binary_sensor.datchik_dvizheniia_prikhozhaia
    to: 'on'
  - platform: state
    entity_id: binary_sensor.pravoe_okno_detskaia
    to: 'on'
  - platform: state
    entity_id: binary_sensor.levoe_okno_detskaia
    to: 'on'
  - platform: state
    entity_id: binary_sensor.levoe_okno_bar
    to: 'on'
  - platform: state
    entity_id: binary_sensor.pravoe_okno_bar
    to: 'on'
  - platform: state
    entity_id: binary_sensor.levoe_okno_fortochka_bar
    to: 'on'
  - platform: state
    entity_id: binary_sensor.levoe_okno_spalnia
    to: 'on'
  - platform: state
    entity_id: binary_sensor.pravoe_okno_spalnia
    to: 'on'
  - platform: state
    entity_id: binary_sensor.dver_spalnia
    to: 'on'
  - platform: state
    entity_id: binary_sensor.dver_tualet
    to: 'on'
  - platform: state
    entity_id: binary_sensor.dver_vannaia
    to: 'on'
  - platform: state
    entity_id: binary_sensor.dver_podezd
    to: 'on'
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: armed_home
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: armed_away
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: armed_night
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.home_alarm
    - service: telegram_bot.send_message
      data:
        title: "<b>ВНИМАНИЕ!!! Запущен таймер сигнализации</b>"
        message: "*У вас есть 30-секунд на выключение*"
        target:
          - !secret telegram_id_1
          - !secret telegram_id_2
        disable_notification: false

- alias: '[ Alarm ] - Triggered'
  trigger:
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    to: triggered
  action:
    - service: telegram_bot.send_message
      data:
        title: "<b>ВНИМАНИЕ!!! Сработала сигнализация</b>"
        message: "*Выключите если это вы*"
        target:
          - !secret telegram_id_1
          - !secret telegram_id_2
        disable_notification: false
    - service: script.yandex_alarm

- alias: '[ Alarm ] - Disarmed'
  id: 118afb36f63a4d8390330c3cf9593d91
  trigger:
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    to: disarmed
  action:
    - service: telegram_bot.send_message
      data:
        title: "<b>Сигнализация</b>"
        message: "*Выключена*"
        target:
          - !secret telegram_id_1
          - !secret telegram_id_2
        disable_notification: false
    - service: script.flick_red_lights
      
 