- alias: "[ GLOBAL ] - Автовыключение света по таймерам"
  id: light-self-shutdown-timer
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id:
      - group.toilet_lights
    to: 'on'
    for: 00:30:00
  - platform: state
    entity_id:
      - group.hall_lights
    to: 'on'
    for: 01:00:00
  - platform: state
    entity_id:
      - group.bath_lights
    to: 'on'
    for: 01:30:00
  action:
  - service: homeassistant.turn_off
    data_template:
      entity_id: '{{ trigger.entity_id }}'
      
